In [38]:
import pandas as pd
import numpy as np

In [45]:
df = pd.read_csv(r"C:\Users\ps302\OneDrive\Desktop\Recommend\src\data\raw\prof\goodData.csv")
df.head(6)

,name,department,expertise,university,doi,raw_json
0,Jaya Madan,Department of Electronics and Communication En...,Electrical and Electronic Engineering,"Chitkara University, Punjab",https://doi.org/10.1109/icaeeci58247.2023.1037...,"{""id"": ""https://openalex.org/W4390551589"", ""do..."
1,Jaya Madan,Department of Electronics and Communication En...,Electrical and Electronic Engineering,"Chitkara University, Punjab",https://doi.org/10.1109/icaeeci58247.2023.1037...,"{""id"": ""https://openalex.org/W4390551589"", ""do..."
2,Jaya Madan,Department of Electronics and Communication En...,Electrical and Electronic Engineering,"Chitkara University, Punjab",https://doi.org/10.1109/incoft60753.2023.10425276,"{""id"": ""https://openalex.org/W4392062995"", ""do..."
3,Jaya Madan,Department of Electronics and Communication En...,Electrical and Electronic Engineering,"Chitkara University, Punjab",https://doi.org/10.1109/incoft60753.2023.10425276,"{""id"": ""https://openalex.org/W4392062995"", ""do..."
4,Jaya Madan,Department of Electronics and Communication En...,Electrical and Electronic Engineering,"Chitkara University, Punjab",https://doi.org/10.1109/smartgencon60755.2023....,"{""id"": ""https://openalex.org/W4392253526"", ""do..."
5,Jaya Madan,Department of Electronics and Communication En...,Electrical and Electronic Engineering,"Chitkara University, Punjab",https://doi.org/10.1109/smartgencon60755.2023....,"{""id"": ""https://openalex.org/W4392253526"", ""do..."

In [40]:
for i in df.iloc[245]:
    print(i)

Gopalan Rajaraman
Department of Chemistry
Computational inorganic chemistry, magnetism and materials science, surface chemistry, calculation of spectral parameters, modelling catalytic reactions in relevance to bioinorganic chemistry.
Indian Institute of Technology Bombay
https://doi.org/10.5517/ccdc.csd.cc1ls9pc
{"id": "https://openalex.org/W4397303203", "doi": "https://doi.org/10.5517/ccdc.csd.cc1ls9pc", "ids": {"doi": "https://doi.org/10.5517/ccdc.csd.cc1ls9pc", "openalex": "https://openalex.org/W4397303203"}, "fwci": null, "mesh": [], "type": "dataset", "title": "CCDC 1483123: Experimental Crystal Structure Determination", "awards": [], "biblio": {"issue": null, "volume": null, "last_page": null, "first_page": null}, "topics": [{"id": "https://openalex.org/T11881", "field": {"id": "https://openalex.org/fields/25", "display_name": "Materials Science"}, "score": 0.991100013256073, "domain": {"id": "https://openalex.org/domains/3", "display_name": "Physical Sciences"}, "subfield": {"id": "https://openalex.org/subfields/2505", "display_name": "Materials Chemistry"}, "display_name": "Crystallization and Solubility Studies"}, {"id": "https://openalex.org/T12613", "field": {"id": "https://openalex.org/fields/25", "display_name": "Materials Science"}, "score": 0.9447000026702881, "domain": {"id": "https://openalex.org/domains/3", "display_name": "Physical Sciences"}, "subfield": {"id": "https://openalex.org/subfields/2505", "display_name": "Materials Chemistry"}, "display_name": "X-ray Diffraction in Crystallography"}], "funders": [], "is_xpac": false, "apc_list": null, "apc_paid": null, "concepts": [{"id": "https://openalex.org/C115624301", "level": 2, "score": 0.45390546321868896, "wikidata": "https://www.wikidata.org/wiki/Q895901", "display_name": "Crystal structure"}, {"id": "https://openalex.org/C8010536", "level": 1, "score": 0.42920973896980286, "wikidata": "https://www.wikidata.org/wiki/Q160398", "display_name": "Crystallography"}, {"id": "https://openalex.org/C192562407", "level": 0, "score": 0.37044113874435425, "wikidata": "https://www.wikidata.org/wiki/Q228736", "display_name": "Materials science"}, {"id": "https://openalex.org/C166957645", "level": 1, "score": 0.3643677532672882, "wikidata": "https://www.wikidata.org/wiki/Q23498", "display_name": "Archaeology"}, {"id": "https://openalex.org/C205649164", "level": 0, "score": 0.3043789863586426, "wikidata": "https://www.wikidata.org/wiki/Q1071", "display_name": "Geography"}, {"id": "https://openalex.org/C185592680", "level": 0, "score": 0.18342313170433044, "wikidata": "https://www.wikidata.org/wiki/Q2329", "display_name": "Chemistry"}], "keywords": [{"id": "https://openalex.org/keywords/crystal-structure", "score": 0.45390546321868896, "display_name": "Crystal structure"}, {"id": "https://openalex.org/keywords/crystallography", "score": 0.42920973896980286, "display_name": "Crystallography"}, {"id": "https://openalex.org/keywords/materials-science", "score": 0.37044113874435425, "display_name": "Materials science"}, {"id": "https://openalex.org/keywords/archaeology", "score": 0.3643677532672882, "display_name": "Archaeology"}, {"id": "https://openalex.org/keywords/geography", "score": 0.3043789863586426, "display_name": "Geography"}, {"id": "https://openalex.org/keywords/chemistry", "score": 0.18342313170433044, "display_name": "Chemistry"}], "language": "en", "locations": [{"id": "doi:10.5517/ccdc.csd.cc1ls9pc", "is_oa": true, "source": {"id": "https://openalex.org/S4397694588", "issn": null, "type": "repository", "is_oa": false, "issn_l": null, "is_core": false, "is_in_doaj": false, "display_name": "The Cambridge Structural Database", "host_organization": "https://openalex.org/I4210098980", "host_organization_name": "Cambridge Crystallographic Data Centre", "host_organization_lineage": ["https://openalex.org/I4210098980"], "host_organization_lineage_names": []}, "license": null, "pdf_url": null, "version": null, "raw_type": "Dataset", "license_id": null, "is_accepted": false, "is_published": null, "raw_source_name": null, "landing_page_url": "https://doi.org/10.5517/ccdc.csd.cc1ls9pc"}], "indexed_in": ["datacite"], "authorships": [{"author": {"id": "https://openalex.org/A5042077606", "orcid": "https://orcid.org/0000-0002-0971-2990", "display_name": "Kuduva R. Vignesh"}, "countries": [], "raw_orcid": null, "affiliations": [], "institutions": [], "author_position": "first", "raw_author_name": "Vignesh, Kuduva R.", "is_corresponding": false, "raw_affiliation_strings": []}, {"author": {"id": "https://openalex.org/A5082883549", "orcid": "https://orcid.org/0000-0002-2241-1551", "display_name": "Stuart K. Langley"}, "countries": [], "raw_orcid": null, "affiliations": [], "institutions": [], "author_position": "middle", "raw_author_name": "Langley, Stuart K.", "is_corresponding": false, "raw_affiliation_strings": []}, {"author": {"id": "https://openalex.org/A5087237293", "orcid": "https://orcid.org/0000-0002-1332-7147", "display_name": "Christopher J. Gartshore"}, "countries": [], "raw_orcid": null, "affiliations": [], "institutions": [], "author_position": "middle", "raw_author_name": "Gartshore, Christopher J.", "is_corresponding": false, "raw_affiliation_strings": []}, {"author": {"id": "https://openalex.org/A5087607114", "orcid": null, "display_name": "Boujemaa Moubaraki"}, "countries": [], "raw_orcid": null, "affiliations": [], "institutions": [], "author_position": "middle", "raw_author_name": "Moubaraki, Boujemaa", "is_corresponding": false, "raw_affiliation_strings": []}, {"author": {"id": "https://openalex.org/A5057309074", "orcid": "https://orcid.org/0000-0003-4098-9389", "display_name": "Keith S. Murray"}, "countries": [], "raw_orcid": null, "affiliations": [], "institutions": [], "author_position": "middle", "raw_author_name": "Murray, Keith S.", "is_corresponding": false, "raw_affiliation_strings": []}, {"author": {"id": "https://openalex.org/A5054818199", "orcid": "https://orcid.org/0000-0001-6133-3026", "display_name": "Gopalan Rajaraman"}, "countries": [], "raw_orcid": null, "affiliations": [], "institutions": [], "author_position": "last", "raw_author_name": "Rajaraman, Gopalan", "is_corresponding": false, "raw_affiliation_strings": []}], "has_content": {"pdf": false, "grobid_xml": false}, "is_paratext": false, "open_access": {"is_oa": true, "oa_url": "https://doi.org/10.5517/ccdc.csd.cc1ls9pc", "oa_status": "green", "any_repository_has_fulltext": true}, "content_urls": null, "created_date": "2025-10-10T00:00:00", "display_name": "CCDC 1483123: Experimental Crystal Structure Determination", "has_fulltext": false, "institutions": [], "is_retracted": false, "updated_date": "2026-07-01T06:00:48.157686", "primary_topic": {"id": "https://openalex.org/T11881", "field": {"id": "https://openalex.org/fields/25", "display_name": "Materials Science"}, "score": 0.991100013256073, "domain": {"id": "https://openalex.org/domains/3", "display_name": "Physical Sciences"}, "subfield": {"id": "https://openalex.org/subfields/2505", "display_name": "Materials Chemistry"}, "display_name": "Crystallization and Solubility Studies"}, "related_works": ["https://openalex.org/W1969352129", "https://openalex.org/W2082823139", "https://openalex.org/W1969215021", "https://openalex.org/W1984275137", "https://openalex.org/W2711806730", "https://openalex.org/W2093692263", "https://openalex.org/W1970277544", "https://openalex.org/W2950637894", "https://openalex.org/W2324887520", "https://openalex.org/W2462612165"], "cited_by_count": 0, "counts_by_year": [], "locations_count": 1, "best_oa_location": {"id": "doi:10.5517/ccdc.csd.cc1ls9pc", "is_oa": true, "source": {"id": "https://openalex.org/S4397694588", "issn": null, "type": "repository", "is_oa": false, "issn_l": null, "is_core": false, "is_in_doaj": false, "display_name": "The Cambridge Structural Database", "host_organization": "https://openalex.org/I4210098980", "host_organization_name": "Cambridge Crystallographic Data Centre", "host_organization_lineage": ["https://openalex.org/I4210098980"], "host_organization_lineage_names": []}, "license": null, "pdf_url": null, "version": null, "raw_type": "Dataset", "license_id": null, "is_accepted": false, "is_published": false, "raw_source_name": null, "landing_page_url": "https://doi.org/10.5517/ccdc.csd.cc1ls9pc"}, "primary_location": {"id": "doi:10.5517/ccdc.csd.cc1ls9pc", "is_oa": true, "source": {"id": "https://openalex.org/S4397694588", "issn": null, "type": "repository", "is_oa": false, "issn_l": null, "is_core": false, "is_in_doaj": false, "display_name": "The Cambridge Structural Database", "host_organization": "https://openalex.org/I4210098980", "host_organization_name": "Cambridge Crystallographic Data Centre", "host_organization_lineage": ["https://openalex.org/I4210098980"], "host_organization_lineage_names": []}, "license": null, "pdf_url": null, "version": null, "raw_type": "Dataset", "license_id": null, "is_accepted": false, "is_published": false, "raw_source_name": null, "landing_page_url": "https://doi.org/10.5517/ccdc.csd.cc1ls9pc"}, "publication_date": "2017-01-01", "publication_year": 2017, "referenced_works": [], "referenced_works_count": 0, "abstract_inverted_index": {"a": [21], "3D": [40], "An": [0], "is": [31], "The": [15, 25], "and": [37, 48], "for": [10, 28], "the": [3, 7, 35], "CCDC": [36], "cell": [42], "data": [19], "from": [2, 20, 34], "this": [29], "entry": [1, 16, 30], "small": [11], "space": [44], "freely": [32], "group,": [45], "study.": [24], "crystal": [13, 22], "dataset": [27], "quality": [49], "contains": [17], "includes": [39], "molecule": [12], "Cambridge": [4], "Database,": [6], "available": [33], "deposited": [26], "measures.": [50], "typically": [38], "world’s": [8], "Structural": [5], "conditions": [47], "repository": [9], "diffraction": [23], "parameters,": [43], "structures.": [14], "coordinates,": [41], "experimental": [18, 46]}, "cited_by_percentile_year": null, "corresponding_author_ids": [], "countries_distinct_count": 0, "institutions_distinct_count": 0, "corresponding_institution_ids": [], "sustainable_development_goals": [], "citation_normalized_percentile": null}

In [44]:
df.at[1, "raw_json"] = json.loads(df.at[1, "raw_json"])
df.at[1, "raw_json"]

{'id': 'https://openalex.org/W4390551589',
 'doi': 'https://doi.org/10.1109/icaeeci58247.2023.10370883',
 'ids': {'doi': 'https://doi.org/10.1109/icaeeci58247.2023.10370883',
  'openalex': 'https://openalex.org/W4390551589'},
 'fwci': None,
 'mesh': [],
 'type': 'conference-paper',
 'title': 'Optimizing Tin-based Solar Cells: Unleashing the Potential of CsSnI<sub>3</sub> Perovskite for a Sustainable Energy Future',
 'awards': [],
 'biblio': {'issue': None, 'volume': '1', 'last_page': '4', 'first_page': '1'},
 'topics': [{'id': 'https://openalex.org/T10247',
   'field': {'id': 'https://openalex.org/fields/22',
    'display_name': 'Engineering'},
   'score': 1.0,
   'domain': {'id': 'https://openalex.org/domains/3',
    'display_name': 'Physical Sciences'},
   'subfield': {'id': 'https://openalex.org/subfields/2208',
    'display_name': 'Electrical and Electronic Engineering'},
   'display_name': 'Perovskite Materials and Applications'},
  {'id': 'https://openalex.org/T10590',
   'field': {'id': 'https://openalex.org/fields/22',
    'display_name': 'Engineering'},
   'score': 0.9965000152587891,
   'domain': {'id': 'https://openalex.org/domains/3',
    'display_name': 'Physical Sciences'},
   'subfield': {'id': 'https://openalex.org/subfields/2208',
    'display_name': 'Electrical and Electronic Engineering'},
   'display_name': 'Chalcogenide Semiconductor Thin Films'},
  {'id': 'https://openalex.org/T10660',
   'field': {'id': 'https://openalex.org/fields/25',
    'display_name': 'Materials Science'},
   'score': 0.9908000230789185,
   'domain': {'id': 'https://openalex.org/domains/3',
    'display_name': 'Physical Sciences'},
   'subfield': {'id': 'https://openalex.org/subfields/2507',
    'display_name': 'Polymers and Plastics'},
   'display_name': 'Conducting polymers and applications'}],
 'funders': [],
 'is_xpac': False,
 'apc_list': None,
 'apc_paid': None,
 'concepts': [{'id': 'https://openalex.org/C525849907',
   'level': 2,
   'score': 0.5911144018173218,
   'wikidata': 'https://www.wikidata.org/wiki/Q1096',
   'display_name': 'Tin'},
  {'id': 'https://openalex.org/C41291067',
   'level': 2,
   'score': 0.4893147647380829,
   'wikidata': 'https://www.wikidata.org/wiki/Q1897785',
   'display_name': 'Photovoltaic system'},
  {'id': 'https://openalex.org/C188573790',
   'level': 2,
   'score': 0.413515567779541,
   'wikidata': 'https://www.wikidata.org/wiki/Q12705',
   'display_name': 'Renewable energy'},
  {'id': 'https://openalex.org/C41008148',
   'level': 0,
   'score': 0.3978671431541443,
   'wikidata': 'https://www.wikidata.org/wiki/Q21198',
   'display_name': 'Computer science'},
  {'id': 'https://openalex.org/C184720557',
   'level': 2,
   'score': 0.37534284591674805,
   'wikidata': 'https://www.wikidata.org/wiki/Q7825049',
   'display_name': 'Topology (electrical circuits)'},
  {'id': 'https://openalex.org/C192562407',
   'level': 0,
   'score': 0.36122435331344604,
   'wikidata': 'https://www.wikidata.org/wiki/Q228736',
   'display_name': 'Materials science'},
  {'id': 'https://openalex.org/C121332964',
   'level': 0,
   'score': 0.3532004952430725,
   'wikidata': 'https://www.wikidata.org/wiki/Q413',
   'display_name': 'Physics'},
  {'id': 'https://openalex.org/C119599485',
   'level': 1,
   'score': 0.34951430559158325,
   'wikidata': 'https://www.wikidata.org/wiki/Q43035',
   'display_name': 'Electrical engineering'},
  {'id': 'https://openalex.org/C11413529',
   'level': 1,
   'score': 0.34947746992111206,
   'wikidata': 'https://www.wikidata.org/wiki/Q8366',
   'display_name': 'Algorithm'},
  {'id': 'https://openalex.org/C185592680',
   'level': 0,
   'score': 0.27717864513397217,
   'wikidata': 'https://www.wikidata.org/wiki/Q2329',
   'display_name': 'Chemistry'},
  {'id': 'https://openalex.org/C127413603',
   'level': 0,
   'score': 0.17867973446846008,
   'wikidata': 'https://www.wikidata.org/wiki/Q11023',
   'display_name': 'Engineering'},
  {'id': 'https://openalex.org/C178790620',
   'level': 1,
   'score': 0.15590012073516846,
   'wikidata': 'https://www.wikidata.org/wiki/Q11351',
   'display_name': 'Organic chemistry'}],
 'keywords': [{'id': 'https://openalex.org/keywords/tin',
   'score': 0.5911144018173218,
   'display_name': 'Tin'},
  {'id': 'https://openalex.org/keywords/photovoltaic-system',
   'score': 0.4893147647380829,
   'display_name': 'Photovoltaic system'},
  {'id': 'https://openalex.org/keywords/renewable-energy',
   'score': 0.413515567779541,
   'display_name': 'Renewable energy'},
  {'id': 'https://openalex.org/keywords/computer-science',
   'score': 0.3978671431541443,
   'display_name': 'Computer science'},
  {'id': 'https://openalex.org/keywords/topology',
   'score': 0.37534284591674805,
   'display_name': 'Topology (electrical circuits)'},
  {'id': 'https://openalex.org/keywords/materials-science',
   'score': 0.36122435331344604,
   'display_name': 'Materials science'},
  {'id': 'https://openalex.org/keywords/physics',
   'score': 0.3532004952430725,
   'display_name': 'Physics'},
  {'id': 'https://openalex.org/keywords/electrical-engineering',
   'score': 0.34951430559158325,
   'display_name': 'Electrical engineering'},
  {'id': 'https://openalex.org/keywords/algorithm',
   'score': 0.34947746992111206,
   'display_name': 'Algorithm'},
  {'id': 'https://openalex.org/keywords/chemistry',
   'score': 0.27717864513397217,
   'display_name': 'Chemistry'},
  {'id': 'https://openalex.org/keywords/engineering',
   'score': 0.17867973446846008,
   'display_name': 'Engineering'},
  {'id': 'https://openalex.org/keywords/organic-chemistry',
   'score': 0.15590012073516846,
   'display_name': 'Organic chemistry'}],
 'language': 'en',
 'locations': [{'id': 'doi:10.1109/icaeeci58247.2023.10370883',
   'is_oa': False,
   'source': None,
   'license': None,
   'pdf_url': None,
   'version': 'publishedVersion',
   'raw_type': 'proceedings-article',
   'license_id': None,
   'is_accepted': True,
   'is_published': True,
   'raw_source_name': '2023 First International Conference on Advances in Electrical, Electronics and Computational Intelligence (ICAEECI)',
   'landing_page_url': 'http://dx.doi.org/10.1109/icaeeci58247.2023.10370883'}],
 'indexed_in': ['crossref'],
 'authorships': [{'author': {'id': 'https://openalex.org/A5073037747',
    'orcid': None,
    'display_name': 'Savita Rawat'},
   'countries': ['IN'],
   'raw_orcid': None,
   'affiliations': [{'institution_ids': ['https://openalex.org/I74319210'],
     'raw_affiliation_string': 'Chitkara University Institute of Engineering &#x0026; Technology, Chitkara University,VLSI Centre of Excellence,Punjab,India'}],
   'institutions': [{'id': 'https://openalex.org/I74319210',
     'ror': 'https://ror.org/057d6z539',
     'type': 'education',
     'lineage': ['https://openalex.org/I74319210'],
     'country_code': 'IN',
     'display_name': 'Chitkara University'}],
   'author_position': 'first',
   'raw_author_name': 'Savita Rawat',
   'is_corresponding': False,
   'raw_affiliation_strings': ['Chitkara University Institute of Engineering &#x0026; Technology, Chitkara University,VLSI Centre of Excellence,Punjab,India']},
  {'author': {'id': 'https://openalex.org/A5027081227',
    'orcid': 'https://orcid.org/0000-0003-4805-9258',
    'display_name': 'Jaya Madan'},
   'countries': ['IN'],
   'raw_orcid': None,
   'affiliations': [{'institution_ids': ['https://openalex.org/I74319210'],
     'raw_affiliation_string': 'Chitkara University Institute of Engineering &#x0026; Technology, Chitkara University,VLSI Centre of Excellence,Punjab,India'}],
   'institutions': [{'id': 'https://openalex.org/I74319210',
     'ror': 'https://ror.org/057d6z539',
     'type': 'education',
     'lineage': ['https://openalex.org/I74319210'],
     'country_code': 'IN',
     'display_name': 'Chitkara University'}],
   'author_position': 'middle',
   'raw_author_name': 'Jaya Madan',
   'is_corresponding': False,
   'raw_affiliation_strings': ['Chitkara University Institute of Engineering &#x0026; Technology, Chitkara University,VLSI Centre of Excellence,Punjab,India']},
  {'author': {'id': 'https://openalex.org/A5003667206',
    'orcid': 'https://orcid.org/0000-0001-7766-3572',
    'display_name': 'Rahul Pandey'},
   'countries': ['IN'],
   'raw_orcid': None,
   'affiliations': [{'institution_ids': ['https://openalex.org/I74319210'],
     'raw_affiliation_string': 'Chitkara University Institute of Engineering &#x0026; Technology, Chitkara University,VLSI Centre of Excellence,Punjab,India'}],
   'institutions': [{'id': 'https://openalex.org/I74319210',
     'ror': 'https://ror.org/057d6z539',
     'type': 'education',
     'lineage': ['https://openalex.org/I74319210'],
     'country_code': 'IN',
     'display_name': 'Chitkara University'}],
   'author_position': 'last',
   'raw_author_name': 'Rahul Pandey',
   'is_corresponding': False,
   'raw_affiliation_strings': ['Chitkara University Institute of Engineering &#x0026; Technology, Chitkara University,VLSI Centre of Excellence,Punjab,India']}],
 'has_content': {'pdf': False, 'grobid_xml': False},
 'is_paratext': False,
 'open_access': {'is_oa': False,
  'oa_url': None,
  'oa_status': 'closed',
  'any_repository_has_fulltext': False},
 'content_urls': None,
 'created_date': '2025-10-10T00:00:00',
 'display_name': 'Optimizing Tin-based Solar Cells: Unleashing the Potential of CsSnI<sub>3</sub> Perovskite for a Sustainable Energy Future',
 'has_fulltext': False,
 'institutions': [],
 'is_retracted': False,
 'updated_date': '2026-07-29T09:40:50.615796',
 'primary_topic': {'id': 'https://openalex.org/T10247',
  'field': {'id': 'https://openalex.org/fields/22',
   'display_name': 'Engineering'},
  'score': 1.0,
  'domain': {'id': 'https://openalex.org/domains/3',
   'display_name': 'Physical Sciences'},
  'subfield': {'id': 'https://openalex.org/subfields/2208',
   'display_name': 'Electrical and Electronic Engineering'},
  'display_name': 'Perovskite Materials and Applications'},
 'related_works': ['https://openalex.org/W2748952813',
  'https://openalex.org/W1148372108',
  'https://openalex.org/W2492470561',
  'https://openalex.org/W2040310861',
  'https://openalex.org/W2273391071',
  'https://openalex.org/W2332218522',
  'https://openalex.org/W2312192749',
  'https://openalex.org/W1983393460',
  'https://openalex.org/W1483162499',
  'https://openalex.org/W4244232650'],
 'cited_by_count': 0,
 'counts_by_year': [],
 'locations_count': 1,
 'best_oa_location': None,
 'primary_location': {'id': 'doi:10.1109/icaeeci58247.2023.10370883',
  'is_oa': False,
  'source': None,
  'license': None,
  'pdf_url': None,
  'version': 'publishedVersion',
  'raw_type': 'proceedings-article',
  'license_id': None,
  'is_accepted': True,
  'is_published': True,
  'raw_source_name': '2023 First International Conference on Advances in Electrical, Electronics and Computational Intelligence (ICAEECI)',
  'landing_page_url': 'http://dx.doi.org/10.1109/icaeeci58247.2023.10370883'},
 'publication_date': '2023-10-19',
 'publication_year': 2023,
 'referenced_works': ['https://openalex.org/W2163551546',
  'https://openalex.org/W2396933094',
  'https://openalex.org/W3041623937',
  'https://openalex.org/W4229021698',
  'https://openalex.org/W4293092914',
  'https://openalex.org/W4297360960',
  'https://openalex.org/W4309645581',
  'https://openalex.org/W4311419982',
  'https://openalex.org/W4361213264',
  'https://openalex.org/W4376112478',
  'https://openalex.org/W4380682524',
  'https://openalex.org/W4383747273',
  'https://openalex.org/W4385412069',
  'https://openalex.org/W6712366592'],
 'referenced_works_count': 14,
 'abstract_inverted_index': {'=': [138, 145, 150, 157],
  'A': [0],
  'a': [18, 34],
  '10': [117],
  '50': [112],
  'PV': [39, 42],
  'an': [180],
  'as': [98],
  'at': [127],
  'be': [33],
  'by': [8],
  'in': [37, 54, 106, 116],
  'is': [6, 85, 125],
  'nm': [115],
  'of': [21, 67, 77, 89, 164, 170],
  'on': [45],
  'to': [32, 73, 113, 173],
  '500': [114, 128],
  'For': [80],
  'PV,': [133],
  'The': [65, 103],
  'Tin': [26],
  'all': [81],
  'and': [2, 56, 152, 167, 175, 183],
  'are': [30, 51, 96],
  'for': [179],
  'has': [70],
  'nm,': [129],
  'not': [59],
  'the': [22, 38, 75, 78, 86, 99, 107, 122, 162, 168],
  'tin': [47],
  'yet': [60],
  '(FF)': [149],
  'ITO/': [91],
  'PSCs': [166],
  'been': [71],
  'fill': [147],
  'from': [111],
  'have': [16, 58],
  'high': [62],
  'open': [141],
  'they': [57],
  'tool': [88],
  '(JSC)': [137],
  '(PCE)': [156],
  '(VOC)': [144],
  '29.17': [139],
  'After': [120],
  'These': [159],
  'based': [44],
  'cells': [29],
  'equal': [118],
  'power': [153],
  'short': [134],
  'solar': [13, 28],
  'still': [52],
  'their': [177],
  'which': [15, 130],
  '0.87V,': [146],
  '86.60%': [151],
  'become': [17],
  'better': [132],
  'cesium': [46],
  'device': [82, 101],
  'energy': [10, 24, 186],
  'factor': [148],
  'future': [5],
  'global': [23],
  'offers': [131],
  'ranges': [110],
  'steps.': [119],
  '22.06%.': [158],
  'choice.': [90],
  'circuit': [135, 142],
  'crucial': [19],
  'current': [136],
  'device.': [79],
  'devices': [43],
  'element': [20],
  'energy,': [14],
  'enhance': [174],
  'examine': [74],
  'future.': [187],
  'layer)/': [94],
  'mA/cm2,': [140],
  'market.': [41],
  'notably': [12],
  'promise': [163],
  'results': [160],
  'thought': [31],
  'voltage': [143],
  '(CsSnI3)': [49],
  'SCAPS-1D': [84],
  'attained': [61],
  "device's": [123],
  'friendly': [182],
  'material': [50],
  'maximize': [176],
  'provided': [7],
  'research': [109, 172],
  'sources,': [11],
  'trailing': [53],
  'conscious': [4],
  'continued': [171],
  'emphasize': [161],
  'influence': [66],
  'optimized': [126],
  'potential': [178],
  'relevance': [169],
  'renewable': [9],
  'suggested': [100, 108],
  'thickness': [68, 105],
  'triiodide': [48],
  '(Sn)-based': [27],
  'PCBM(ETL)/': [92],
  'challenger': [36],
  'conversion': [63, 154],
  'efficiency': [155],
  'researched': [72],
  'simulation': [87],
  'structure.': [102],
  'HTL(Cul)/Au': [95],
  'competitive': [35],
  'constructed': [97],
  'efficiency.': [64],
  'performance': [124],
  'responsible': [185],
  'revolution.': [25],
  'sustainable': [1],
  'variability': [69],
  'CsSnI3-based': [165],
  'ecologically': [184],
  'performance,': [55],
  'simulations,': [83],
  'effectiveness': [76],
  '(photovoltaic)': [40],
  'experimenting,': [121],
  'CsSnI3(Absorber': [93],
  'environmentally': [3, 181],
  "CsSnI3absorber's": [104]},
 'cited_by_percentile_year': None,
 'corresponding_author_ids': [],
 'countries_distinct_count': 1,
 'institutions_distinct_count': 1,
 'corresponding_institution_ids': ['https://openalex.org/I74319210'],
 'sustainable_development_goals': [],
 'citation_normalized_percentile': None}

In [4]:
for i in df.iloc[245]:
    print(i)

Gopalan Rajaraman
Department of Chemistry
Computational inorganic chemistry, magnetism and materials science, surface chemistry, calculation of spectral parameters, modelling catalytic reactions in relevance to bioinorganic chemistry.
Indian Institute of Technology Bombay
https://doi.org/10.5517/ccdc.csd.cc1ls9pc
{"id": "https://openalex.org/W4397303203", "doi": "https://doi.org/10.5517/ccdc.csd.cc1ls9pc", "ids": {"doi": "https://doi.org/10.5517/ccdc.csd.cc1ls9pc", "openalex": "https://openalex.org/W4397303203"}, "fwci": null, "mesh": [], "type": "dataset", "title": "CCDC 1483123: Experimental Crystal Structure Determination", "awards": [], "biblio": {"issue": null, "volume": null, "last_page": null, "first_page": null}, "topics": [{"id": "https://openalex.org/T11881", "field": {"id": "https://openalex.org/fields/25", "display_name": "Materials Science"}, "score": 0.991100013256073, "domain": {"id": "https://openalex.org/domains/3", "display_name": "Physical Sciences"}, "subfield": {"id": "https://openalex.org/subfields/2505", "display_name": "Materials Chemistry"}, "display_name": "Crystallization and Solubility Studies"}, {"id": "https://openalex.org/T12613", "field": {"id": "https://openalex.org/fields/25", "display_name": "Materials Science"}, "score": 0.9447000026702881, "domain": {"id": "https://openalex.org/domains/3", "display_name": "Physical Sciences"}, "subfield": {"id": "https://openalex.org/subfields/2505", "display_name": "Materials Chemistry"}, "display_name": "X-ray Diffraction in Crystallography"}], "funders": [], "is_xpac": false, "apc_list": null, "apc_paid": null, "concepts": [{"id": "https://openalex.org/C115624301", "level": 2, "score": 0.45390546321868896, "wikidata": "https://www.wikidata.org/wiki/Q895901", "display_name": "Crystal structure"}, {"id": "https://openalex.org/C8010536", "level": 1, "score": 0.42920973896980286, "wikidata": "https://www.wikidata.org/wiki/Q160398", "display_name": "Crystallography"}, {"id": "https://openalex.org/C192562407", "level": 0, "score": 0.37044113874435425, "wikidata": "https://www.wikidata.org/wiki/Q228736", "display_name": "Materials science"}, {"id": "https://openalex.org/C166957645", "level": 1, "score": 0.3643677532672882, "wikidata": "https://www.wikidata.org/wiki/Q23498", "display_name": "Archaeology"}, {"id": "https://openalex.org/C205649164", "level": 0, "score": 0.3043789863586426, "wikidata": "https://www.wikidata.org/wiki/Q1071", "display_name": "Geography"}, {"id": "https://openalex.org/C185592680", "level": 0, "score": 0.18342313170433044, "wikidata": "https://www.wikidata.org/wiki/Q2329", "display_name": "Chemistry"}], "keywords": [{"id": "https://openalex.org/keywords/crystal-structure", "score": 0.45390546321868896, "display_name": "Crystal structure"}, {"id": "https://openalex.org/keywords/crystallography", "score": 0.42920973896980286, "display_name": "Crystallography"}, {"id": "https://openalex.org/keywords/materials-science", "score": 0.37044113874435425, "display_name": "Materials science"}, {"id": "https://openalex.org/keywords/archaeology", "score": 0.3643677532672882, "display_name": "Archaeology"}, {"id": "https://openalex.org/keywords/geography", "score": 0.3043789863586426, "display_name": "Geography"}, {"id": "https://openalex.org/keywords/chemistry", "score": 0.18342313170433044, "display_name": "Chemistry"}], "language": "en", "locations": [{"id": "doi:10.5517/ccdc.csd.cc1ls9pc", "is_oa": true, "source": {"id": "https://openalex.org/S4397694588", "issn": null, "type": "repository", "is_oa": false, "issn_l": null, "is_core": false, "is_in_doaj": false, "display_name": "The Cambridge Structural Database", "host_organization": "https://openalex.org/I4210098980", "host_organization_name": "Cambridge Crystallographic Data Centre", "host_organization_lineage": ["https://openalex.org/I4210098980"], "host_organization_lineage_names": []}, "license": null, "pdf_url": null, "version": null, "raw_type": "Dataset", "license_id": null, "is_accepted": false, "is_published": null, "raw_source_name": null, "landing_page_url": "https://doi.org/10.5517/ccdc.csd.cc1ls9pc"}], "indexed_in": ["datacite"], "authorships": [{"author": {"id": "https://openalex.org/A5042077606", "orcid": "https://orcid.org/0000-0002-0971-2990", "display_name": "Kuduva R. Vignesh"}, "countries": [], "raw_orcid": null, "affiliations": [], "institutions": [], "author_position": "first", "raw_author_name": "Vignesh, Kuduva R.", "is_corresponding": false, "raw_affiliation_strings": []}, {"author": {"id": "https://openalex.org/A5082883549", "orcid": "https://orcid.org/0000-0002-2241-1551", "display_name": "Stuart K. Langley"}, "countries": [], "raw_orcid": null, "affiliations": [], "institutions": [], "author_position": "middle", "raw_author_name": "Langley, Stuart K.", "is_corresponding": false, "raw_affiliation_strings": []}, {"author": {"id": "https://openalex.org/A5087237293", "orcid": "https://orcid.org/0000-0002-1332-7147", "display_name": "Christopher J. Gartshore"}, "countries": [], "raw_orcid": null, "affiliations": [], "institutions": [], "author_position": "middle", "raw_author_name": "Gartshore, Christopher J.", "is_corresponding": false, "raw_affiliation_strings": []}, {"author": {"id": "https://openalex.org/A5087607114", "orcid": null, "display_name": "Boujemaa Moubaraki"}, "countries": [], "raw_orcid": null, "affiliations": [], "institutions": [], "author_position": "middle", "raw_author_name": "Moubaraki, Boujemaa", "is_corresponding": false, "raw_affiliation_strings": []}, {"author": {"id": "https://openalex.org/A5057309074", "orcid": "https://orcid.org/0000-0003-4098-9389", "display_name": "Keith S. Murray"}, "countries": [], "raw_orcid": null, "affiliations": [], "institutions": [], "author_position": "middle", "raw_author_name": "Murray, Keith S.", "is_corresponding": false, "raw_affiliation_strings": []}, {"author": {"id": "https://openalex.org/A5054818199", "orcid": "https://orcid.org/0000-0001-6133-3026", "display_name": "Gopalan Rajaraman"}, "countries": [], "raw_orcid": null, "affiliations": [], "institutions": [], "author_position": "last", "raw_author_name": "Rajaraman, Gopalan", "is_corresponding": false, "raw_affiliation_strings": []}], "has_content": {"pdf": false, "grobid_xml": false}, "is_paratext": false, "open_access": {"is_oa": true, "oa_url": "https://doi.org/10.5517/ccdc.csd.cc1ls9pc", "oa_status": "green", "any_repository_has_fulltext": true}, "content_urls": null, "created_date": "2025-10-10T00:00:00", "display_name": "CCDC 1483123: Experimental Crystal Structure Determination", "has_fulltext": false, "institutions": [], "is_retracted": false, "updated_date": "2026-07-01T06:00:48.157686", "primary_topic": {"id": "https://openalex.org/T11881", "field": {"id": "https://openalex.org/fields/25", "display_name": "Materials Science"}, "score": 0.991100013256073, "domain": {"id": "https://openalex.org/domains/3", "display_name": "Physical Sciences"}, "subfield": {"id": "https://openalex.org/subfields/2505", "display_name": "Materials Chemistry"}, "display_name": "Crystallization and Solubility Studies"}, "related_works": ["https://openalex.org/W1969352129", "https://openalex.org/W2082823139", "https://openalex.org/W1969215021", "https://openalex.org/W1984275137", "https://openalex.org/W2711806730", "https://openalex.org/W2093692263", "https://openalex.org/W1970277544", "https://openalex.org/W2950637894", "https://openalex.org/W2324887520", "https://openalex.org/W2462612165"], "cited_by_count": 0, "counts_by_year": [], "locations_count": 1, "best_oa_location": {"id": "doi:10.5517/ccdc.csd.cc1ls9pc", "is_oa": true, "source": {"id": "https://openalex.org/S4397694588", "issn": null, "type": "repository", "is_oa": false, "issn_l": null, "is_core": false, "is_in_doaj": false, "display_name": "The Cambridge Structural Database", "host_organization": "https://openalex.org/I4210098980", "host_organization_name": "Cambridge Crystallographic Data Centre", "host_organization_lineage": ["https://openalex.org/I4210098980"], "host_organization_lineage_names": []}, "license": null, "pdf_url": null, "version": null, "raw_type": "Dataset", "license_id": null, "is_accepted": false, "is_published": false, "raw_source_name": null, "landing_page_url": "https://doi.org/10.5517/ccdc.csd.cc1ls9pc"}, "primary_location": {"id": "doi:10.5517/ccdc.csd.cc1ls9pc", "is_oa": true, "source": {"id": "https://openalex.org/S4397694588", "issn": null, "type": "repository", "is_oa": false, "issn_l": null, "is_core": false, "is_in_doaj": false, "display_name": "The Cambridge Structural Database", "host_organization": "https://openalex.org/I4210098980", "host_organization_name": "Cambridge Crystallographic Data Centre", "host_organization_lineage": ["https://openalex.org/I4210098980"], "host_organization_lineage_names": []}, "license": null, "pdf_url": null, "version": null, "raw_type": "Dataset", "license_id": null, "is_accepted": false, "is_published": false, "raw_source_name": null, "landing_page_url": "https://doi.org/10.5517/ccdc.csd.cc1ls9pc"}, "publication_date": "2017-01-01", "publication_year": 2017, "referenced_works": [], "referenced_works_count": 0, "abstract_inverted_index": {"a": [21], "3D": [40], "An": [0], "is": [31], "The": [15, 25], "and": [37, 48], "for": [10, 28], "the": [3, 7, 35], "CCDC": [36], "cell": [42], "data": [19], "from": [2, 20, 34], "this": [29], "entry": [1, 16, 30], "small": [11], "space": [44], "freely": [32], "group,": [45], "study.": [24], "crystal": [13, 22], "dataset": [27], "quality": [49], "contains": [17], "includes": [39], "molecule": [12], "Cambridge": [4], "Database,": [6], "available": [33], "deposited": [26], "measures.": [50], "typically": [38], "world’s": [8], "Structural": [5], "conditions": [47], "repository": [9], "diffraction": [23], "parameters,": [43], "structures.": [14], "coordinates,": [41], "experimental": [18, 46]}, "cited_by_percentile_year": null, "corresponding_author_ids": [], "countries_distinct_count": 0, "institutions_distinct_count": 0, "corresponding_institution_ids": [], "sustainable_development_goals": [], "citation_normalized_percentile": null}

In [5]:
type(df.iloc[245]["raw_json"])

str

In [46]:
def inverted_index_to_text(inverted_index):
    if not inverted_index:
        return ""

    # Find the highest word position
    max_position = max(
        pos
        for positions in inverted_index.values()
        for pos in positions
    )

    # Create empty list for words
    words = [None] * (max_position + 1)

    # Put each word back at its original position
    for word, positions in inverted_index.items():
        for pos in positions:
            words[pos] = word

    # Join words into normal text
    return " ".join(words)

In [7]:
import json

def openalex_abstract_from_string(json_string):
    # JSON string → Python dictionary
    data = json.loads(json_string)

    # Get inverted index
    inverted_index = data.get("abstract_inverted_index")

    if not inverted_index:
        return None

    # Find maximum word position
    max_position = max(
        pos
        for positions in inverted_index.values()
        for pos in positions
    )

    # Reconstruct word order
    words = [None] * (max_position + 1)

    for word, positions in inverted_index.items():
        for pos in positions:
            words[pos] = word

    return " ".join(words)

In [47]:
df.head()

,name,department,expertise,university,doi,raw_json
0,Jaya Madan,Department of Electronics and Communication En...,Electrical and Electronic Engineering,"Chitkara University, Punjab",https://doi.org/10.1109/icaeeci58247.2023.1037...,"{""id"": ""https://openalex.org/W4390551589"", ""do..."
1,Jaya Madan,Department of Electronics and Communication En...,Electrical and Electronic Engineering,"Chitkara University, Punjab",https://doi.org/10.1109/icaeeci58247.2023.1037...,"{""id"": ""https://openalex.org/W4390551589"", ""do..."
2,Jaya Madan,Department of Electronics and Communication En...,Electrical and Electronic Engineering,"Chitkara University, Punjab",https://doi.org/10.1109/incoft60753.2023.10425276,"{""id"": ""https://openalex.org/W4392062995"", ""do..."
3,Jaya Madan,Department of Electronics and Communication En...,Electrical and Electronic Engineering,"Chitkara University, Punjab",https://doi.org/10.1109/incoft60753.2023.10425276,"{""id"": ""https://openalex.org/W4392062995"", ""do..."
4,Jaya Madan,Department of Electronics and Communication En...,Electrical and Electronic Engineering,"Chitkara University, Punjab",https://doi.org/10.1109/smartgencon60755.2023....,"{""id"": ""https://openalex.org/W4392253526"", ""do..."

In [9]:
# use_00
name = df.loc[22,"name"]
expertise = df.loc[22, "expertise"]
department = df.loc[22, "department"]

In [10]:
# use_05
content = openalex_abstract_from_string((df.iloc[22]["raw_json"]))

In [12]:
df.at[22, "raw_json"] = json.loads(df.at[22, "raw_json"])
df.at[22, "raw_json"]

{'id': 'https://openalex.org/W4403678665',
 'doi': 'https://doi.org/10.1109/i-smac61858.2024.10714848',
 'ids': {'doi': 'https://doi.org/10.1109/i-smac61858.2024.10714848',
  'openalex': 'https://openalex.org/W4403678665'},
 'fwci': None,
 'mesh': [],
 'type': 'conference-paper',
 'title': 'Improving the Performance of Cs<sub>2</sub>AgBiBr<sub>6</sub> Perovskite Solar Cells by Investigating the Effect of Temperature',
 'awards': [],
 'biblio': {'issue': None,
  'volume': None,
  'last_page': '374',
  'first_page': '371'},
 'topics': [{'id': 'https://openalex.org/T10247',
   'field': {'id': 'https://openalex.org/fields/22',
    'display_name': 'Engineering'},
   'score': 0.9926999807357788,
   'domain': {'id': 'https://openalex.org/domains/3',
    'display_name': 'Physical Sciences'},
   'subfield': {'id': 'https://openalex.org/subfields/2208',
    'display_name': 'Electrical and Electronic Engineering'},
   'display_name': 'Perovskite Materials and Applications'}],
 'funders': [{'id': 'https://openalex.org/F4320323432',
   'ror': 'https://ror.org/057d6z539',
   'display_name': 'Chitkara University'}],
 'is_xpac': False,
 'apc_list': None,
 'apc_paid': None,
 'concepts': [{'id': 'https://openalex.org/C155011858',
   'level': 2,
   'score': 0.7340317964553833,
   'wikidata': 'https://www.wikidata.org/wiki/Q3036449',
   'display_name': 'Perovskite (structure)'},
  {'id': 'https://openalex.org/C192562407',
   'level': 0,
   'score': 0.5621353983879089,
   'wikidata': 'https://www.wikidata.org/wiki/Q228736',
   'display_name': 'Materials science'},
  {'id': 'https://openalex.org/C72293138',
   'level': 2,
   'score': 0.4730645418167114,
   'wikidata': 'https://www.wikidata.org/wiki/Q909741',
   'display_name': 'Temperature measurement'},
  {'id': 'https://openalex.org/C49040817',
   'level': 1,
   'score': 0.4641386866569519,
   'wikidata': 'https://www.wikidata.org/wiki/Q193091',
   'display_name': 'Optoelectronics'},
  {'id': 'https://openalex.org/C41008148',
   'level': 0,
   'score': 0.40448424220085144,
   'wikidata': 'https://www.wikidata.org/wiki/Q21198',
   'display_name': 'Computer science'},
  {'id': 'https://openalex.org/C61696701',
   'level': 1,
   'score': 0.3975308835506439,
   'wikidata': 'https://www.wikidata.org/wiki/Q770766',
   'display_name': 'Engineering physics'},
  {'id': 'https://openalex.org/C39432304',
   'level': 0,
   'score': 0.33224165439605713,
   'wikidata': 'https://www.wikidata.org/wiki/Q188847',
   'display_name': 'Environmental science'},
  {'id': 'https://openalex.org/C121332964',
   'level': 0,
   'score': 0.27667659521102905,
   'wikidata': 'https://www.wikidata.org/wiki/Q413',
   'display_name': 'Physics'},
  {'id': 'https://openalex.org/C185592680',
   'level': 0,
   'score': 0.1613905429840088,
   'wikidata': 'https://www.wikidata.org/wiki/Q2329',
   'display_name': 'Chemistry'},
  {'id': 'https://openalex.org/C8010536',
   'level': 1,
   'score': 0.15354058146476746,
   'wikidata': 'https://www.wikidata.org/wiki/Q160398',
   'display_name': 'Crystallography'},
  {'id': 'https://openalex.org/C97355855',
   'level': 1,
   'score': 0.14396139979362488,
   'wikidata': 'https://www.wikidata.org/wiki/Q11473',
   'display_name': 'Thermodynamics'}],
 'keywords': [{'id': 'https://openalex.org/keywords/perovskite',
   'score': 0.7340317964553833,
   'display_name': 'Perovskite (structure)'},
  {'id': 'https://openalex.org/keywords/materials-science',
   'score': 0.5621353983879089,
   'display_name': 'Materials science'},
  {'id': 'https://openalex.org/keywords/temperature-measurement',
   'score': 0.4730645418167114,
   'display_name': 'Temperature measurement'},
  {'id': 'https://openalex.org/keywords/optoelectronics',
   'score': 0.4641386866569519,
   'display_name': 'Optoelectronics'},
  {'id': 'https://openalex.org/keywords/computer-science',
   'score': 0.40448424220085144,
   'display_name': 'Computer science'},
  {'id': 'https://openalex.org/keywords/engineering-physics',
   'score': 0.3975308835506439,
   'display_name': 'Engineering physics'},
  {'id': 'https://openalex.org/keywords/environmental-science',
   'score': 0.33224165439605713,
   'display_name': 'Environmental science'},
  {'id': 'https://openalex.org/keywords/physics',
   'score': 0.27667659521102905,
   'display_name': 'Physics'},
  {'id': 'https://openalex.org/keywords/chemistry',
   'score': 0.1613905429840088,
   'display_name': 'Chemistry'},
  {'id': 'https://openalex.org/keywords/crystallography',
   'score': 0.15354058146476746,
   'display_name': 'Crystallography'},
  {'id': 'https://openalex.org/keywords/thermodynamics',
   'score': 0.14396139979362488,
   'display_name': 'Thermodynamics'}],
 'language': 'en',
 'locations': [{'id': 'doi:10.1109/i-smac61858.2024.10714848',
   'is_oa': False,
   'source': None,
   'license': None,
   'pdf_url': None,
   'version': 'publishedVersion',
   'raw_type': 'proceedings-article',
   'license_id': None,
   'is_accepted': True,
   'is_published': True,
   'raw_source_name': '2024 8th International Conference on I-SMAC (IoT in Social, Mobile, Analytics and Cloud) (I-SMAC)',
   'landing_page_url': 'https://doi.org/10.1109/i-smac61858.2024.10714848'}],
 'indexed_in': ['crossref'],
 'authorships': [{'author': {'id': 'https://openalex.org/A5073037747',
    'orcid': None,
    'display_name': 'Savita Rawat'},
   'countries': ['IN'],
   'raw_orcid': None,
   'affiliations': [{'institution_ids': ['https://openalex.org/I74319210'],
     'raw_affiliation_string': 'Chitkara University Institute of Engineering &#x0026; Technology, Chitkara University,VLSI Centre of Excellence,Punjab,India'}],
   'institutions': [{'id': 'https://openalex.org/I74319210',
     'ror': 'https://ror.org/057d6z539',
     'type': 'education',
     'lineage': ['https://openalex.org/I74319210'],
     'country_code': 'IN',
     'display_name': 'Chitkara University'}],
   'author_position': 'first',
   'raw_author_name': 'Savita Rawat',
   'is_corresponding': False,
   'raw_affiliation_strings': ['Chitkara University Institute of Engineering &#x0026; Technology, Chitkara University,VLSI Centre of Excellence,Punjab,India']},
  {'author': {'id': 'https://openalex.org/A5027081227',
    'orcid': 'https://orcid.org/0000-0003-4805-9258',
    'display_name': 'Jaya Madan'},
   'countries': ['IN'],
   'raw_orcid': None,
   'affiliations': [{'institution_ids': ['https://openalex.org/I74319210'],
     'raw_affiliation_string': 'Chitkara University Institute of Engineering &#x0026; Technology, Chitkara University,VLSI Centre of Excellence,Punjab,India'}],
   'institutions': [{'id': 'https://openalex.org/I74319210',
     'ror': 'https://ror.org/057d6z539',
     'type': 'education',
     'lineage': ['https://openalex.org/I74319210'],
     'country_code': 'IN',
     'display_name': 'Chitkara University'}],
   'author_position': 'middle',
   'raw_author_name': 'Jaya Madan',
   'is_corresponding': False,
   'raw_affiliation_strings': ['Chitkara University Institute of Engineering &#x0026; Technology, Chitkara University,VLSI Centre of Excellence,Punjab,India']},
  {'author': {'id': 'https://openalex.org/A5102979649',
    'orcid': 'https://orcid.org/0009-0005-5041-9728',
    'display_name': 'Aniket Verma'},
   'countries': ['IN'],
   'raw_orcid': None,
   'affiliations': [{'institution_ids': ['https://openalex.org/I74319210'],
     'raw_affiliation_string': 'Chitkara University Institute of Engineering &#x0026; Technology, Chitkara University,VLSI Centre of Excellence,Punjab,India'}],
   'institutions': [{'id': 'https://openalex.org/I74319210',
     'ror': 'https://ror.org/057d6z539',
     'type': 'education',
     'lineage': ['https://openalex.org/I74319210'],
     'country_code': 'IN',
     'display_name': 'Chitkara University'}],
   'author_position': 'last',
   'raw_author_name': 'Aniket Verma',
   'is_corresponding': False,
   'raw_affiliation_strings': ['Chitkara University Institute of Engineering &#x0026; Technology, Chitkara University,VLSI Centre of Excellence,Punjab,India']}],
 'has_content': {'pdf': False, 'grobid_xml': False},
 'is_paratext': False,
 'open_access': {'is_oa': False,
  'oa_url': None,
  'oa_status': 'closed',
  'any_repository_has_fulltext': False},
 'content_urls': None,
 'created_date': '2025-10-10T00:00:00',
 'display_name': 'Improving the Performance of Cs<sub>2</sub>AgBiBr<sub>6</sub> Perovskite Solar Cells by Investigating the Effect of Temperature',
 'has_fulltext': False,
 'institutions': [],
 'is_retracted': False,
 'updated_date': '2026-07-29T09:40:50.615796',
 'primary_topic': {'id': 'https://openalex.org/T10247',
  'field': {'id': 'https://openalex.org/fields/22',
   'display_name': 'Engineering'},
  'score': 0.9926999807357788,
  'domain': {'id': 'https://openalex.org/domains/3',
   'display_name': 'Physical Sciences'},
  'subfield': {'id': 'https://openalex.org/subfields/2208',
   'display_name': 'Electrical and Electronic Engineering'},
  'display_name': 'Perovskite Materials and Applications'},
 'related_works': ['https://openalex.org/W2796035869',
  'https://openalex.org/W3013428864',
  'https://openalex.org/W2515631532',
  'https://openalex.org/W644652328',
  'https://openalex.org/W2921596481',
  'https://openalex.org/W4386267073',
  'https://openalex.org/W4387686786',
  'https://openalex.org/W4384912300',
  'https://openalex.org/W2835213954',
  'https://openalex.org/W4281634175'],
 'cited_by_count': 0,
 'counts_by_year': [],
 'locations_count': 1,
 'best_oa_location': None,
 'primary_location': {'id': 'doi:10.1109/i-smac61858.2024.10714848',
  'is_oa': False,
  'source': None,
  'license': None,
  'pdf_url': None,
  'version': 'publishedVersion',
  'raw_type': 'proceedings-article',
  'license_id': None,
  'is_accepted': True,
  'is_published': True,
  'raw_source_name': '2024 8th International Conference on I-SMAC (IoT in Social, Mobile, Analytics and Cloud) (I-SMAC)',
  'landing_page_url': 'https://doi.org/10.1109/i-smac61858.2024.10714848'},
 'publication_date': '2024-10-03',
 'publication_year': 2024,
 'referenced_works': ['https://openalex.org/W2403824339',
  'https://openalex.org/W2584786362',
  'https://openalex.org/W2750598354',
  'https://openalex.org/W2891146712',
  'https://openalex.org/W2917762001',
  'https://openalex.org/W4205834404',
  'https://openalex.org/W4282561512',
  'https://openalex.org/W4319082738',
  'https://openalex.org/W4377704389',
  'https://openalex.org/W4388672854',
  'https://openalex.org/W4390550802',
  'https://openalex.org/W4392459003',
  'https://openalex.org/W4393204827',
  'https://openalex.org/W4393971395'],
 'referenced_works_count': 14,
 'abstract_inverted_index': {'K': [160],
  'a': [60, 88, 178, 193, 238, 242, 250],
  'FF': [246],
  'In': [99],
  'PV': [115, 230, 275],
  'an': [92, 245],
  'as': [59, 75],
  'at': [232],
  'be': [143, 177],
  'by': [170],
  'go': [129],
  'in': [145, 161, 188, 263],
  'is': [16, 105, 149, 167, 237, 277],
  'it': [118],
  'of': [2, 28, 35, 111, 131, 196, 199, 216, 247, 252, 280],
  'on': [94, 113],
  'to': [11, 49, 63, 69, 107, 120, 128, 158, 176, 210, 222, 274],
  '240': [157],
  '340': [159],
  'PCE': [251],
  'The': [0, 79, 138, 184, 205],
  'and': [32, 51, 134, 151, 214, 249],
  'are': [19, 56, 125, 228],
  'but': [54],
  'can': [220],
  'due': [10],
  'for': [192],
  'has': [7, 86],
  'how': [132],
  'its': [76],
  'the': [40,
   71,
   102,
   109,
   114,
   126,
   146,
   152,
   181,
   197,
   208,
   212,
   229,
   257,
   261,
   278],
  'two': [182],
  'way': [127, 209],
  '(PV)': [73],
  '21.1': [240],
  '350K': [233],
  'Here': [227],
  'PSCs': [95, 124],
  'This': [15, 66],
  'When': [117],
  'aims': [68],
  'are.': [137],
  'best': [168],
  'come': [87],
  'from': [97, 156],
  'goal': [279],
  'have': [42],
  'here': [82],
  'lead': [50, 221],
  'long': [89],
  'made': [96],
  'more': [223],
  'that': [84, 141],
  'they': [136],
  'this': [100, 281],
  'used': [106, 144],
  'way,': [90],
  'will': [142, 154],
  'with': [21, 91],
  'JSCof': [239],
  'Solar': [164],
  'There': [236],
  'VOCof': [243],
  'about': [47],
  'allow': [191],
  'cells': [25],
  'cheap': [135],
  'comes': [119],
  'green': [122],
  'range': [155],
  'shows': [83],
  'since': [173],
  'solar': [24, 64],
  'study': [67, 148],
  'their': [29, 36],
  'there': [18, 174],
  'toxic': [30],
  'under': [201],
  'which': [219],
  '(PSCs)': [26],
  '1.31V,': [244],
  '22.2%.': [253],
  'Making': [271],
  'become': [8],
  'cells,': [218],
  'design': [140],
  'device': [139],
  'energy': [165, 225, 269],
  'issues': [20],
  'modern': [12],
  'nature': [31],
  'power,': [123],
  'within': [256],
  '10-step': [162],
  '79.54%,': [248],
  'Because': [34],
  'Careful': [254],
  'ambient': [234],
  'analyze': [70],
  'appears': [175],
  'because': [17, 27, 130],
  'between': [180],
  'diverse': [202],
  'effort.': [282],
  'energy.': [65],
  'enhance': [211],
  'examine': [108],
  'focused': [194],
  'gaining': [57],
  'mA/cm2,': [241],
  'primary': [77],
  'program': [104],
  'remain,': [53],
  'studies': [264],
  'varying': [185],
  '1D-SCAPS': [103],
  'Concerns': [46],
  'advances': [262],
  'efficacy': [198],
  'emphasis': [93],
  'existing': [258],
  'exposure': [48],
  'findings': [206],
  'options,': [4],
  'purpose.': [78],
  'research': [80],
  'settings': [190],
  'sources.': [226, 270],
  'absorbent': [38],
  'attention': [58],
  'concerns.': [14],
  'efficient': [133],
  'emergence': [1],
  'endurance': [52],
  'excellent': [37],
  'highlight': [207],
  'including': [5],
  'influence': [110],
  'inorganic': [267],
  'lead-free': [3],
  'long-term': [272],
  'materials': [200],
  'optimized': [169],
  'potential': [61],
  'presented': [81],
  'producing': [121],
  'renewable': [224],
  'structure': [213],
  'suggested': [147],
  'concerning': [265],
  'highlights': [260],
  'lead-based': [22],
  'literature': [259],
  'perovskite': [23, 268],
  'potential.': [45],
  'production': [166],
  'properties': [74, 231],
  'remarkable': [43],
  'technology': [276],
  'variables.': [183],
  'Cs2AgBiBr6.': [98],
  'alternative': [62],
  'controlling': [171],
  'efficiency,': [39],
  'examination': [195],
  'experiment,': [101],
  'increments.': [163],
  'performance': [215],
  'properties.': [116],
  'significant': [9],
  'situations.': [204],
  'temperature': [112, 172, 186, 203],
  'experimental': [189],
  'fluctuations': [187],
  'improvements': [273],
  'instability.': [33],
  'photovoltaic': [72],
  'relationship': [179],
  'temperature:': [235],
  'temperatures': [153],
  'environmental': [13],
  'photovoltaics': [85],
  'suncollecting': [44],
  'Cs2AgBiBr6PSCs': [55],
  'Cs2AgBiBr6solar': [217],
  'safe-to-consume': [266],
  'contextualization': [255],
  'Cs2AgBiBr6compounds': [41],
  'Cs2AgBiBr6perovskites,': [6],
  'Al/FTO/CdS/Cs2AgBiBr6/Ni,': [150]},
 'cited_by_percentile_year': None,
 'corresponding_author_ids': [],
 'countries_distinct_count': 1,
 'institutions_distinct_count': 1,
 'corresponding_institution_ids': ['https://openalex.org/I74319210'],
 'sustainable_development_goals': [{'id': 'https://metadata.un.org/sdg/7',
   'score': 0.7300000190734863,
   'display_name': 'Affordable and clean energy'}],
 'citation_normalized_percentile': None}

In [13]:
# use_01
title = df.at[22, "raw_json"]["title"]
print(title)

Improving the Performance of Cs<sub>2</sub>AgBiBr<sub>6</sub> Perovskite Solar Cells by Investigating the Effect of Temperature

In [14]:
for i in df.at[22, "raw_json"]["topics"]:
    print(i)

{'id': 'https://openalex.org/T10247', 'field': {'id': 'https://openalex.org/fields/22', 'display_name': 'Engineering'}, 'score': 0.9926999807357788, 'domain': {'id': 'https://openalex.org/domains/3', 'display_name': 'Physical Sciences'}, 'subfield': {'id': 'https://openalex.org/subfields/2208', 'display_name': 'Electrical and Electronic Engineering'}, 'display_name': 'Perovskite Materials and Applications'}

In [15]:
# use_02
topics_display_name = set()
for i in df.at[22, "raw_json"]["topics"]:
    # print(i["field"]["display_name"])
    # print(i["domain"]["display_name"])
    # print(i["subfield"]["display_name"])
    # print(i["display_name"])
    topics_display_name.add(i["field"]["display_name"])
    topics_display_name.add(i["domain"]["display_name"])
    topics_display_name.add(i["subfield"]["display_name"])
    topics_display_name.add(i["display_name"])
topics_display_name

{'Electrical and Electronic Engineering',
 'Engineering',
 'Perovskite Materials and Applications',
 'Physical Sciences'}

In [16]:
# use_03
concepts_display_name = set()
for i in df.at[22, "raw_json"]["concepts"]:
    # print(i["display_name"])
    concepts_display_name.add(i["display_name"])
concepts_display_name

{'Chemistry',
 'Computer science',
 'Crystallography',
 'Engineering physics',
 'Environmental science',
 'Materials science',
 'Optoelectronics',
 'Perovskite (structure)',
 'Physics',
 'Temperature measurement',
 'Thermodynamics'}

In [ ]:
# use_04
primary_topics_display_name = set()
for i in df.at[22, "raw_json"]["concepts"]:
    primary_topics_display_name.add(i["display_name"])
    
primary_topics_display_name

{'Chemical engineering',
 'Colloid',
 'Dispersity',
 'Emulsion',
 'Engineering',
 'Evaporation',
 'Kinetics',
 'Materials science',
 'Nanoparticle',
 'Nanotechnology',
 'Optoelectronics',
 'Ostwald ripening',
 'Physics',
 'Pickering emulsion',
 'Polymer chemistry',
 'Quantum mechanics',
 'Superlattice',
 'Thermodynamics'}

In [77]:
# openalex_abstract_from_string(df.iloc[22]["raw_json"])

In [61]:
import json
import pandas as pd


def inverted_index_to_text(inverted_index):
    """Convert OpenAlex abstract_inverted_index to normal text."""
    
    if not inverted_index:
        return None

    max_position = max(
        pos
        for positions in inverted_index.values()
        for pos in positions
    )

    words = [None] * (max_position + 1)

    for word, positions in inverted_index.items():
        for pos in positions:
            words[pos] = word

    return " ".join(word for word in words if word is not None)


def process_openalex_row(row):
    """Extract all required information from one OpenAlex row."""

    raw_json = row["raw_json"]

    # If raw_json is a JSON string, convert it to dict
    if isinstance(raw_json, str):
        try:
            raw_json = json.loads(raw_json)
        except json.JSONDecodeError:
            raw_json = {}

    if raw_json.get("type") != "dataset":
        # -------------------------
        # Basic information
        # -------------------------
        name = row.get("name")
        expertise = row.get("expertise")
        department = row.get("department")

        # -------------------------
        # Title
        # -------------------------
        title = raw_json.get("title")

        # -------------------------
        # Topics
        # -------------------------
        topics_display_name = set()

        for topic in raw_json.get("topics", []):
            if topic.get("field"):
                topics_display_name.add(
                    topic["field"].get("display_name")
                )

            if topic.get("domain"):
                topics_display_name.add(
                    topic["domain"].get("display_name")
                )

            if topic.get("subfield"):
                topics_display_name.add(
                    topic["subfield"].get("display_name")
                )

            if topic.get("display_name"):
                topics_display_name.add(
                    topic["display_name"]
                )

        # Remove None
        topics_display_name.discard(None)

        # -------------------------
        # Concepts
        # -------------------------
        concepts_display_name = set()

        for concept in raw_json.get("concepts", []):
            if concept.get("display_name"):
                concepts_display_name.add(
                    concept["display_name"]
                )

        # -------------------------
        # Primary Topics
        # -------------------------
        # Your original code was using concepts here.
        # Keeping it exactly as you wrote it.
        primary_topics_display_name = set()

        for concept in raw_json.get("concepts", []):
            if concept.get("display_name"):
                primary_topics_display_name.add(
                    concept["display_name"]
                )

        # -------------------------
        # Abstract
        # -------------------------
        abstract_inverted_index = raw_json.get(
            "abstract_inverted_index"
        )

        abstract = inverted_index_to_text(
            abstract_inverted_index
        )

    # -------------------------
    # Return one row
    # -------------------------
        return {
            "name": name,
            "expertise": expertise,
            "department": department,
            "title": title,
            "topics_display_name": topics_display_name,
            "concepts_display_name": concepts_display_name,
            "primary_topics_display_name": primary_topics_display_name,
            "abstract": abstract
        }
    else:
        pass

In [62]:
final_df = df.apply(process_openalex_row, axis=1, result_type="expand")
# print(final_df)
final_df.head()

,name,expertise,department,title,topics_display_name,concepts_display_name,primary_topics_display_name,abstract
0,Jaya Madan,Electrical and Electronic Engineering,Department of Electronics and Communication En...,Optimizing Tin-based Solar Cells: Unleashing t...,"{Physical Sciences, Materials Science, Enginee...","{Materials science, Organic chemistry, Renewab...","{Materials science, Organic chemistry, Renewab...",A sustainable and environmentally conscious fu...
1,Jaya Madan,Electrical and Electronic Engineering,Department of Electronics and Communication En...,Optimizing Tin-based Solar Cells: Unleashing t...,"{Physical Sciences, Materials Science, Enginee...","{Materials science, Organic chemistry, Renewab...","{Materials science, Organic chemistry, Renewab...",A sustainable and environmentally conscious fu...
2,Jaya Madan,Electrical and Electronic Engineering,Department of Electronics and Communication En...,Enhancing Photovoltaic Performance of Lead-Fre...,"{Physical Sciences, Materials Chemistry, Quant...","{Engineering physics, Optoelectronics, Materia...","{Engineering physics, Optoelectronics, Materia...",Tin-based photovoltaic (PV) cells have become ...
3,Jaya Madan,Electrical and Electronic Engineering,Department of Electronics and Communication En...,Enhancing Photovoltaic Performance of Lead-Fre...,"{Physical Sciences, Materials Chemistry, Quant...","{Engineering physics, Optoelectronics, Materia...","{Engineering physics, Optoelectronics, Materia...",Tin-based photovoltaic (PV) cells have become ...
4,Jaya Madan,Electrical and Electronic Engineering,Department of Electronics and Communication En...,Enhancing the Performance of CsSnCl<sub>3</sub...,"{Physical Sciences, Materials Chemistry, Mater...","{Optoelectronics, Materials science, Perovskit...","{Optoelectronics, Materials science, Perovskit...","Recently, there has been a lot of interest in ..."

In [64]:
final_df = final_df.dropna(how="all")
len(final_df)

18696

In [65]:
len(final_df)

18696

In [ ]:
# len(final_df)

20000

In [69]:
final_df.to_csv(r"C:\Users\ps302\OneDrive\Desktop\Recommend\src\data\processed\prof\extracted_03_prof_data.csv", index=False)

In [70]:
# df = pd.read_csv("data.csv", usecols=lambda col: col != "ID")

# Loads everything EXCEPT 'ID' and 'Address'
final_df = pd.read_csv(
    r"C:\Users\ps302\OneDrive\Desktop\Recommend\src\data\processed\prof\extracted_03_prof_data.csv", 
    usecols=lambda col: col not in ["Unnamed: 0"]
)

final_df.sample(4)

,name,expertise,department,title,topics_display_name,concepts_display_name,primary_topics_display_name,abstract
16060,Harish Kumar,"Mechanical measurement and metrology, Additive...",Department of Mechanical and Aerospace Enginee...,Laser generated TiC reinforced with Fe-Al matr...,"{'Advanced Welding Techniques Analysis', 'Phys...","{'Composite material', 'Materials science', 'L...","{'Composite material', 'Materials science', 'L...",This paper deals with the study of Al-Si alloy...
9849,Bijaya Ketan Panigrahi,"Power Quality, FACTS Devices, Power System Pro...",Department of Electrical Engineering,Operation window constrained strategic energy ...,"{'Physical Sciences', 'Smart Grid Energy Manag...","{'Energy (signal processing)', 'Business', 'Wi...","{'Energy (signal processing)', 'Business', 'Wi...","In this study, an operation window constrained..."
1844,Perumal Yogeeswari,"Drug Design and Synthesis, Drug Screening",Department of Pharmacy,Design and Synthesis of New Etodolac‐Pyridazin...,"{'Synthesis and Biological Evaluation', 'Pharm...","{'Stereochemistry', 'Hydrazide', 'Organic chem...","{'Stereochemistry', 'Hydrazide', 'Organic chem...",Abstract Pb(OAc) 4 to assist N−N bond formatio...
3509,Rajeev Ahuja,Prof. Rajeev Ahuja is a Professor of Computati...,Department of Physics,Rashba Triggered Electronic and Optical Proper...,"{'Physical Sciences', 'Materials Chemistry', '...","{'Optoelectronics', 'Materials science', 'Cond...","{'Optoelectronics', 'Materials science', 'Cond...",The inherent spin–orbit coupling (SOC) effect ...

In [74]:
final_df.to_csv(r"C:\Users\ps302\OneDrive\Desktop\Recommend\src\data\processed\prof\extracted_04_prof_data.csv", index=False)

In [81]:
temp = final_df.loc[final_df["name"] == "Balasubramanian P"]
temp.iloc[1]

name                                                           Balasubramanian P
expertise                      User studies,  Information and                ...
department                                                 Department of Library
title                          Antibody Response to Respiratory Syncytial Vir...
topics_display_name            {'Influenza Virus Research Studies', 'Respirat...
concepts_display_name          {'Virology', 'Antibody response', 'Vaccination...
primary_topics_display_name    {'Virology', 'Antibody response', 'Vaccination...
abstract                       This prospective study investigates antibody r...
Name: 15251, dtype: object

In [72]:
final_df = final_df.drop_duplicates()
len(final_df)

9313

In [73]:
len(final_df)

9313

In [33]:
final_df.isnull().sum()

name                            0
expertise                       0
department                     80
title                           0
topics_display_name             0
concepts_display_name           0
primary_topics_display_name     0
abstract                        1
dtype: int64

In [ ]:
# # 1. Rows with ANY null values in any column
# any_null_index = df.index[df.isna().any(axis=1)]

# # 2. Rows where ALL values are null
# all_null_index = df.index[df.isna().all(axis=1)]

# 3. Rows with null values in a SPECIFIC column 
col_null_index = final_df.index[final_df['abstract'].isna()]
print(col_null_index)
final_df.iloc[col_null_index]

Index([6159], dtype='int64')

,name,expertise,department,title,topics_display_name,concepts_display_name,primary_topics_display_name,abstract
12345,Suddhasatwa Basu,Hydrogen Energy and Fuel Cell Technology.,Department of Chemical Engineering,Passivation of Extended Defects in Silicon by ...,"{'Physical Sciences', 'Engineering', 'Electric...","{'Silicon', 'Materials science', 'Organic chem...","{'Silicon', 'Materials science', 'Organic chem...",This paper reports the results of a new hydrog...