In [1]:
import numpy as np
import pandas as pd
import torch
import json
from collections import defaultdict
from sklearn.preprocessing import StandardScaler

In [2]:
import json
with open(r"C:\Users\ps302\OneDrive\Desktop\Recommend\src\data\processed\vocab_dict_data\categorical_maps.json", "rb") as file:
    categorical_maps = json.load(file)
categorical_maps

{'department': {'Agricultural Engineering': 1,
  'Agricultural Sciences': 2,
  'Agricultural and Biological Engineering': 3,
  'Agricultural and Environmental Sciences': 4,
  'Agronomy': 5,
  'Amity Institute of Applied Sciences (Noida)': 6,
  'Amity School of Physical Sciences': 7,
  'Amrut Mody School of Management': 8,
  'Biochemistry': 9,
  'Bioinformatics': 10,
  'Bioinformatics and Computational Biology': 11,
  'Biological Engineering': 12,
  'Biological Sciences': 13,
  'Chemical Engineering': 14,
  'Chemical and Biochemical Processing Division': 15,
  'Chemistry': 16,
  'Civil and Environmental Engineering': 17,
  'Computational Biology': 18,
  'Computer Science': 19,
  'Computer Science and Artificial Intelligence Laboratory': 20,
  'Computer Science and Artificial Intelligence Laboratory (CSAIL)': 21,
  'Computer Science and Engineering': 22,
  'Computer Science and Media Arts': 23,
  'Computer Science and Media Lab': 24,
  'Computer Science and Technology': 25,
  'Department of Agricultural Engineering': 26,
  'Department of Agricultural Sciences': 27,
  'Department of Agricultural and Biological Engineering': 28,
  'Department of Agricultural and Environmental Engineering': 29,
  'Department of Agricultural and Environmental Sciences': 30,
  'Department of Agricultural and Resource Economics': 31,
  'Department of Agronomy': 32,
  'Department of Agronomy and Food Systems': 33,
  'Department of Agronomy and Plant Science': 34,
  'Department of Agronomy and Soil Science': 35,
  'Department of Anthropology': 36,
  'Department of Applied Mathematics': 37,
  'Department of Biochemistry': 38,
  'Department of Bioengineering': 39,
  'Department of Bioinformatics': 40,
  'Department of Bioinformatics and Computational Biology': 41,
  'Department of Bioinformatics and Systems Biology': 42,
  'Department of Biological Engineering': 43,
  'Department of Biotechnology': 44,
  'Department of Botany (Lumami Campus)': 45,
  'Department of Chemical Engineering': 46,
  'Department of Chemistry': 47,
  'Department of Civil and Environmental Engineering': 48,
  'Department of Computational Biology': 49,
  'Department of Computer Application': 50,
  'Department of Computer Science': 51,
  'Department of Computer Science and Engineering': 52,
  'Department of Earth Sciences': 53,
  'Department of Economics': 54,
  'Department of Economics and Public Policy': 55,
  'Department of Economics, University of Cambridge': 56,
  'Department of Electrical Engineering': 57,
  'Department of Electrical Engineering and Computer Sciences': 58,
  'Department of Electrical and Electronics Engineering': 59,
  'Department of Electronics and Communication Engineering': 60,
  'Department of Electronics and Telecommunication Engineering': 61,
  'Department of Engineering': 62,
  'Department of Engineering (Geography and Earth Sciences)': 63,
  'Department of Engineering (Geospatial Engineering)': 64,
  'Department of Environmental Sciences': 65,
  'Department of Food Engineering and Technology': 66,
  'Department of Food Engineering and Technology (खाद्य अभियांत्रकी और प्रौद्योगिकी)': 67,
  'Department of Genetics': 68,
  'Department of Geography': 69,
  'Department of Geography and Environmental Engineering': 70,
  'Department of Information Technology': 71,
  'Department of Library': 72,
  'Department of Mathematics': 73,
  'Department of Mechanical Engineering': 74,
  'Department of Mechanical and Aerospace Engineering': 75,
  'Department of Pathology Division': 76,
  'Department of Pediatrics': 77,
  'Department of Pharmaceutical Technology': 78,
  'Department of Pharmaceutics': 79,
  'Department of Pharmacy': 80,
  'Department of Physics': 81,
  'Department of Plant Breeding and Genetics': 82,
  'Department of Plant Genetics and Genomics': 83,
  'Department of Plant Pathology': 84,
  'Department of Plant Sciences': 85,
  'Department of Plant and Microbial Biology': 86,
  'Department of Plant and Microbial Sciences': 87,
  'Department of Plant and Soil Sciences': 88,
  'Department of Political Science': 89,
  'Department of Sociology': 90,
  'Department of Soil Science': 91,
  'Department of Soil Science & Microbial Ecology': 92,
  'Department of Soil Science and Agricultural Chemistry': 93,
  'Department of Soil Science and Climate Change': 94,
  'Department of Soil Science and Crop Ecology': 95,
  'Department of Soil Science and Crop Sciences': 96,
  'Department of Soil Science and Environment': 97,
  'Department of Soil Science and Environmental Management': 98,
  'Department of Soil Science and Environmental Microbiology': 99,
  'Department of Soil Science and Environmental Sustainability': 100,
  'Department of Soil Science and Microbial Ecology': 101,
  'Department of Soil Science and Plant Biology': 102,
  'Department of Soil Science and Plant Breeding': 103,
  'Department of Soil Science and Plant Nutrition': 104,
  'Department of Soil and Crop Sciences': 105,
  'Department of Soil, Water and Atmosphere': 106,
  'Department of Soil, Water and Atmospheric Research': 107,
  'Department of Soil, Water and Environmental Sciences': 108,
  'Department of Soil, Water, and Plant Sciences': 109,
  'Department of Urban Studies and Planning': 110,
  'Earth Sciences': 111,
  'Earth Sciences and Engineering': 112,
  'Economics': 113,
  'Economics and Policy': 114,
  'Electrical Engineering': 115,
  'Electrical Engineering and Computer Science': 116,
  'Electrical and Computer Engineering': 117,
  'Engineering': 118,
  'Environmental Sciences': 119,
  'Faculty of Economics': 120,
  'Genetics & Plant Breeding': 121,
  'Geographic Information Science': 122,
  'Geography': 123,
  'Geography and Geospatial Engineering': 124,
  'Geography and Planning': 125,
  'Informatics and Big Data': 126,
  'Institute Instrumentation Centre': 127,
  'Institute for Data, Systems, and Society (IDSS)': 128,
  'Institute of Technology': 129,
  'Materials Chemistry': 130,
  'Materials Research Centre': 131,
  'Materials Science and Engineering': 132,
  'Mechanical Engineering': 133,
  'Media Arts & Sciences': 134,
  'Media Arts and Sciences': 135,
  'Media Lab, MIT': 136,
  'Physics': 137,
  'Physics Group': 138,
  'Plant Breeding and Genetics': 139,
  'Plant Genetics and Breeding': 140,
  'Plant Sciences': 141,
  'Public Policy': 142,
  'School of Advanced Chemical Sciences': 143,
  'School of Physical Sciences': 144,
  'Sociology': 145,
  'Soil Science': 146,
  'Soil Science & Plant Nutrition': 147,
  'Soil Science and Environmental Management': 148,
  'Soil Science and Plant Nutrition': 149,
  'Soil and Environmental Sciences': 150,
  'Soil, Water and Environment': 151,
  'UNKNOWN': 0},
 'university': {'Carnegie Mellon University': 1,
  'Cornell University': 2,
  'Imperial College London': 3,
  'London School of Economics': 4,
  'London School of Economics and Political Science': 5,
  'MIT': 6,
  'Massachusetts Institute of Technology': 7,
  'Stanford University': 8,
  'Technical University of Munich': 9,
  'University College London': 10,
  'University of British Columbia': 11,
  'University of California, Berkeley': 12,
  'University of California, Davis': 13,
  'University of Cambridge': 14,
  'University of Chicago': 15,
  'University of Copenhagen': 16,
  'University of Illinois Urbana-Champaign': 17,
  'University of Illinois Urbana‑Champaign': 18,
  'University of Michigan': 19,
  'University of Oxford': 20,
  'University of Queensland': 21,
  'University of Reading': 22,
  'Wageningen University': 23,
  'Wageningen University & Research': 24,
  'UNKNOWN': 0},
 'country': {'Australia': 1,
  'Canada': 2,
  'Denmark': 3,
  'Germany': 4,
  'Netherlands': 5,
  'United Kingdom': 6,
  'United States': 7,
  'UNKNOWN': 0},
 'sub_domain': {'AI & Autonomous Systems': 1,
  'Computational Social Science': 2,
  'Heterogeneous Catalysis': 3,
  'Precision Agronomy': 4,
  'Synthetic Biology': 5,
  'UNKNOWN': 0},
 'category': {'Agricultural Sciences': 1,
  'Biological Sciences': 2,
  'Chemical Sciences': 3,
  'Engineering & Technology': 4,
  'Social Sciences': 5,
  'UNKNOWN': 0}}

In [3]:
PHD_prefinal_dataset = defaultdict()

In [4]:
df = pd.read_json(r"C:\Users\ps302\OneDrive\Desktop\Recommend\src\data\processed\phd\sop\gpt_extracted_data.json")
df.head()

,name,research_interests,expertise,department,university,country,publications,publication_count,citation_count,years_experience,sop_paragraphs,category,sub_domain,scholar_id,source_file,sop_paragraphs_json,full_sop_markdown,word_count
0,Maya L. Patel,"[Autonomous navigation for aerial robotics, Mu...","[Python, C++, Robot Operating System (ROS), Te...",Electrical and Computer Engineering,Stanford University,United States,[Learning Safe Maneuvers for Quadrotor Swarms ...,2,34,3,[From watching a flock of drones weave through...,Engineering & Technology,AI & Autonomous Systems,150,generated_sop_150.pdf,"[""From watching a flock of drones weave throug...",From watching a flock of drones weave through ...,430
1,Alejandro R. Gómez,[Satellite remote sensing for climate change m...,"[Python, R, MATLAB, Google Earth Engine, ENVI,...",Civil and Environmental Engineering,University of Cambridge,United Kingdom,[Deep Learning‑Based Atmospheric Correction fo...,2,21,4,[When I first examined a series of Sentinel‑2 ...,Engineering & Technology,AI & Autonomous Systems,151,generated_sop_151.pdf,"[""When I first examined a series of Sentinel\u...",When I first examined a series of Sentinel‑2 i...,445
2,Aisha Khan,"[Autonomous navigation for aerial robotics, Mu...","[Python, C++, Robot Operating System (ROS), Te...",Electrical and Computer Engineering,Massachusetts Institute of Technology,United States,[Learning Safe Maneuvers for Quadrotor Swarms ...,2,27,3,[From the moment I programmed my first line‑of...,Engineering & Technology,AI & Autonomous Systems,152,generated_sop_152.pdf,"[""From the moment I programmed my first line\u...",From the moment I programmed my first line‑of‑...,453
3,Mateo Alvarez,[Satellite remote sensing for environmental mo...,"[Python (NumPy, Pandas, Scikit‑learn), R (sp, ...",Civil and Environmental Engineering,University of Cambridge,United Kingdom,[Integrating SAR and Optical Data for Flood Ma...,3,45,4,"[Growing up along the Pacific coast of Chile, ...",Engineering & Technology,AI & Autonomous Systems,153,generated_sop_153.pdf,"[""Growing up along the Pacific coast of Chile,...","Growing up along the Pacific coast of Chile, I...",443
4,Aria L. Chen,[Robust perception for autonomous aerial vehic...,"[Python, C++, ROS2, TensorFlow, PyTorch, JAX, ...",Electrical Engineering and Computer Science,Massachusetts Institute of Technology,United States,[Safe Multi‑Agent Reinforcement Learning for U...,3,27,4,[From the moment I piloted a quadcopter throug...,Engineering & Technology,AI & Autonomous Systems,154,generated_sop_154.pdf,"[""From the moment I piloted a quadcopter throu...",From the moment I piloted a quadcopter through...,479

In [5]:
# Categorcial Data -> 
categorical_col = ["department", "university", "country", "sub_domain", "category"]
# df1 = df[["department", "university", "country", "sub_domain", "category"]]
# df2 = prof_df[["department"]]
# df2.head()

In [6]:
import pandas as pd
import torch

def preprocess_categorical_dataset(df, categorical_cols, categorical_maps, id_col="scholar_id", device=None):
    """
    Maps categorical columns to IDs, converts each row's categorical IDs to a PyTorch tensor,
    and returns a list of dictionaries in the format: {id_col: val, 'cat_ids': tensor([...])}
    """
    if device is None:
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        
    # 1. Map all categorical columns in a vectorized way
    mapped_df = pd.DataFrame(index=df.index)
    for col in categorical_cols:
        col_map = categorical_maps.get(col, {})
        # Map values to their IDs, defaulting to 0 (UNKNOWN's ID) if not found
        mapped_df[col] = (
            df[col]
            .fillna("UNKNOWN")
            .astype(str)
            .map(lambda x: col_map.get(x, col_map.get("UNKNOWN", 0)))
        )
    
    # 2. Convert mapped values to a 2D numpy array, then to a PyTorch tensor
    # Shape of all_cat_tensors: (num_rows, num_categorical_columns)
    all_cat_tensors = torch.tensor(mapped_df[categorical_cols].values, dtype=torch.long, device=device)
    
    # 3. Assemble the final list of dicts
    prefinal_dataset = []
    ids = df[id_col].values
    
    for idx, row_id in enumerate(ids):
        prefinal_dataset.append({
            id_col: int(row_id),
            "cat_ids": all_cat_tensors[idx] # Slice the tensor for the current row
        })
        
    return prefinal_dataset

In [7]:
# Select the device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Run the pre-processing function
PHD_prefinal_dataset = preprocess_categorical_dataset(
    df=df,
    categorical_cols=categorical_col,
    categorical_maps=categorical_maps,
    id_col="scholar_id",
    device=device
)

# Example output verification:
print("First item in the dataset:")
print(PHD_prefinal_dataset[0])

First item in the dataset:
{'scholar_id': 150, 'cat_ids': tensor([117,   8,   7,   1,   4])}

In [ ]:
# PHD_prefinal_dataset

{'scholar_id': 150, 'cat_ids': tensor([117,   8,   7,   1,   4])}

In [ ]:
# df.head()

,name,research_interests,expertise,department,university,country,publications,publication_count,citation_count,years_experience,sop_paragraphs,category,sub_domain,scholar_id,source_file,sop_paragraphs_json,full_sop_markdown,word_count
0,Maya L. Patel,"[Autonomous navigation for aerial robotics, Mu...","[Python, C++, Robot Operating System (ROS), Te...",Electrical and Computer Engineering,Stanford University,United States,[Learning Safe Maneuvers for Quadrotor Swarms ...,2,34,3,[From watching a flock of drones weave through...,Engineering & Technology,AI & Autonomous Systems,150,generated_sop_150.pdf,"[""From watching a flock of drones weave throug...",From watching a flock of drones weave through ...,430
1,Alejandro R. Gómez,[Satellite remote sensing for climate change m...,"[Python, R, MATLAB, Google Earth Engine, ENVI,...",Civil and Environmental Engineering,University of Cambridge,United Kingdom,[Deep Learning‑Based Atmospheric Correction fo...,2,21,4,[When I first examined a series of Sentinel‑2 ...,Engineering & Technology,AI & Autonomous Systems,151,generated_sop_151.pdf,"[""When I first examined a series of Sentinel\u...",When I first examined a series of Sentinel‑2 i...,445
2,Aisha Khan,"[Autonomous navigation for aerial robotics, Mu...","[Python, C++, Robot Operating System (ROS), Te...",Electrical and Computer Engineering,Massachusetts Institute of Technology,United States,[Learning Safe Maneuvers for Quadrotor Swarms ...,2,27,3,[From the moment I programmed my first line‑of...,Engineering & Technology,AI & Autonomous Systems,152,generated_sop_152.pdf,"[""From the moment I programmed my first line\u...",From the moment I programmed my first line‑of‑...,453
3,Mateo Alvarez,[Satellite remote sensing for environmental mo...,"[Python (NumPy, Pandas, Scikit‑learn), R (sp, ...",Civil and Environmental Engineering,University of Cambridge,United Kingdom,[Integrating SAR and Optical Data for Flood Ma...,3,45,4,"[Growing up along the Pacific coast of Chile, ...",Engineering & Technology,AI & Autonomous Systems,153,generated_sop_153.pdf,"[""Growing up along the Pacific coast of Chile,...","Growing up along the Pacific coast of Chile, I...",443
4,Aria L. Chen,[Robust perception for autonomous aerial vehic...,"[Python, C++, ROS2, TensorFlow, PyTorch, JAX, ...",Electrical Engineering and Computer Science,Massachusetts Institute of Technology,United States,[Safe Multi‑Agent Reinforcement Learning for U...,3,27,4,[From the moment I piloted a quadcopter throug...,Engineering & Technology,AI & Autonomous Systems,154,generated_sop_154.pdf,"[""From the moment I piloted a quadcopter throu...",From the moment I piloted a quadcopter through...,479

In [8]:
import torch


def append_categorical_embeddings(
    prefinal_dataset, categorical_cols, categorical_encoder, device=None
):
    """Batches the 'cat_ids' from the prefinal_dataset, runs them through the

    categorical_encoder, and appends the resulting normalized embedding as
    'cat_emb' to each row.
    """
    if len(prefinal_dataset) == 0:
        return prefinal_dataset

    if device is None:
        # Automatically detect the device from the encoder parameters
        device = next(categorical_encoder.parameters()).device

    # 1. Stack all 'cat_ids' tensors into a single 2D tensor
    # Shape: (num_rows, num_columns)
    cat_ids_stacked = torch.stack(
        [item["cat_ids"] for item in prefinal_dataset]
    ).to(device)

    # 2. Build the dictionary expected by the encoder's forward pass
    categorical_inputs = {}
    for idx, col in enumerate(categorical_cols):
        # Slice the column dimension for all rows: Shape (num_rows,)
        categorical_inputs[col] = cat_ids_stacked[:, idx]

    # 3. Run the forward pass with gradients disabled
    categorical_encoder.eval()
    with torch.no_grad():
        # Shape: (num_rows, num_columns * 32)
        all_embeddings = categorical_encoder(categorical_inputs)

    # 4. Append each row's 1D embedding tensor to the dataset dicts
    for idx, item in enumerate(prefinal_dataset):
        # Shape: (num_columns * 32,)
        item["cat_emb"] = all_embeddings[idx]

    return prefinal_dataset

In [17]:
import sys
import os

# Use __file__ if running as a script, fallback to os.getcwd() in Jupyter notebook
try:
    notebook_dir = os.path.dirname(os.path.abspath(__file__))
except NameError:
    notebook_dir = os.getcwd()

# Go up two levels from 'src/utils' to reach the project root directory
project_root = os.path.abspath(os.path.join(notebook_dir, "..", ".."))

if project_root not in sys.path:
    sys.path.append(project_root)

from src.model_utils.query_tower_utils.categorical_encoder import QueryCategoricalEncoder
from src.model_utils.query_tower_utils.numerical_encoder import QueryNumercalEncoder
# from src.model_utils.query_tower_utils.numerical_encoder import QueryNumericalEncoder

In [12]:
# 1. Instantiate the encoder and move it to the device
# Note: The QueryCategoricalEncoder class in categorical_encoder.py handles embedding_dim=32 by default
categorical_encoder = QueryCategoricalEncoder(categorical_maps).to(device)

# 2. Append 'cat_emb' to your existing PHD_prefinal_dataset
PHD_prefinal_dataset = append_categorical_embeddings(
    prefinal_dataset=PHD_prefinal_dataset,
    categorical_cols=categorical_col, # e.g., ["department", "university", "country"]
    categorical_encoder=categorical_encoder,
    device=device
)

# 3. Verify the result
print("First row of the updated dataset:")
print(PHD_prefinal_dataset[0].keys())
print("cat_emb shape:", PHD_prefinal_dataset[0]["cat_emb"].shape)

First row of the updated dataset:
dict_keys(['scholar_id', 'cat_ids', 'cat_emb'])
cat_emb shape: torch.Size([160])

In [14]:
PHD_prefinal_dataset[0]

{'scholar_id': 150,
 'cat_ids': tensor([117,   8,   7,   1,   4]),
 'cat_emb': tensor([-0.0536, -0.1200, -0.0054,  0.0758, -0.0147,  0.0565, -0.0610, -0.0036,
         -0.0930,  0.0555, -0.0396,  0.0412, -0.0317, -0.0834,  0.0974, -0.1482,
         -0.0185,  0.0415, -0.1815, -0.1261,  0.0252, -0.0825, -0.0374,  0.0390,
          0.0032, -0.0658,  0.0674,  0.0053, -0.0444,  0.0385, -0.0905, -0.0797,
          0.0449,  0.1074,  0.0917, -0.0215,  0.0486,  0.0277,  0.0064,  0.0375,
         -0.0416,  0.0087, -0.0865,  0.0190, -0.1329, -0.0959,  0.0765,  0.0646,
          0.0882,  0.0114,  0.1502, -0.0247, -0.0753, -0.0546, -0.0567, -0.0513,
          0.0158, -0.0493,  0.1088, -0.0347,  0.0529,  0.0226,  0.0123,  0.0998,
          0.1051,  0.1086,  0.0592,  0.0393, -0.0944,  0.0304, -0.0555,  0.1885,
         -0.0316,  0.0072,  0.0061, -0.0697,  0.0126, -0.0754, -0.0975,  0.0199,
         -0.0057, -0.0091, -0.0711, -0.0760, -0.0594, -0.0393,  0.1275, -0.0041,
          0.0191, -0.0218,  0.0371, -0.1475, -0.0278, -0.0055, -0.0208, -0.0383,
          0.1104, -0.0897, -0.0134,  0.0986, -0.0167, -0.1240, -0.0402,  0.0817,
          0.0786,  0.0206, -0.0644,  0.0908, -0.0307,  0.0619, -0.0023, -0.1582,
          0.1232, -0.0190,  0.0354,  0.1289,  0.0103, -0.0127,  0.0616,  0.0534,
         -0.2264, -0.0565,  0.0650,  0.0426,  0.0432,  0.1340,  0.0062,  0.0010,
          0.0799,  0.0255, -0.0961, -0.0693, -0.0630, -0.0672, -0.0335, -0.0940,
          0.0190, -0.0975, -0.0441,  0.0439, -0.0459,  0.0576,  0.0728, -0.0134,
          0.0217,  0.0523,  0.0700,  0.1442,  0.0844, -0.0224, -0.0177, -0.0837,
         -0.0817,  0.1942, -0.2464,  0.0871, -0.0607,  0.0609, -0.1500, -0.2187])}

In [19]:
from sklearn.preprocessing import StandardScaler
import pandas as pd
import torch


def append_numerical_features(
    prefinal_dataset, df, numerical_cols, numerical_encoder, scaler=None, device=None
):
    """Cleans numerical columns (converting 'UNK' or other strings to 0), scales

    them, runs them through the numerical encoder, and appends 'num_ids' (scaled
    values) and 'num_emb' (numerical embeddings) to each row in the dataset.
    """
    if len(prefinal_dataset) == 0:
        return prefinal_dataset, scaler

    if device is None:
        device = next(numerical_encoder.parameters()).device

    # 1. Clean the numerical columns: convert strings like 'UNK' to NaN and fill with 0
    clean_df = pd.DataFrame(index=df.index)
    for col in numerical_cols:
        clean_df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0.0)

    # 2. Scale the cleaned numerical columns
    if scaler is None:
        scaler = StandardScaler()
        numeric_values = scaler.fit_transform(clean_df[numerical_cols])
    else:
        numeric_values = scaler.transform(clean_df[numerical_cols])

    # Convert to PyTorch float32 tensor
    numeric_tensor = torch.tensor(
        numeric_values, dtype=torch.float32, device=device
    )

    # 3. Run the numerical encoder
    numerical_encoder.eval()
    with torch.no_grad():
        numerical_embeddings = numerical_encoder(numeric_tensor)

    # 4. Append 'num_ids' and 'num_emb' to each row
    for idx, item in enumerate(prefinal_dataset):
        item["num_ids"] = numeric_tensor[idx]
        item["num_emb"] = numerical_embeddings[idx]

    return prefinal_dataset, scaler

In [20]:
numerical_col = ["publication_count", "years_experience", "citation_count"]
# 1. Instantiate the numerical encoder model and move to device
numerical_encoder = QueryNumercalEncoder(
    input_dim=len(numerical_col), 
    output_dim=32
).to(device)

# 2. Append the numerical values and embeddings
PHD_prefinal_dataset, fitted_scaler = append_numerical_features(
    prefinal_dataset=PHD_prefinal_dataset,
    df=df,
    numerical_cols=numerical_col, # ["publication_count", "years_experience", "citation_count"]
    numerical_encoder=numerical_encoder,
    scaler=None, # Will fit a new StandardScaler internally
    device=device
)

# 3. Verify the result
print("First row keys in the updated dataset:")
print(PHD_prefinal_dataset[0].keys())
print("num_ids (scaled inputs):", PHD_prefinal_dataset[0]["num_ids"])
print("num_emb (embedding):", PHD_prefinal_dataset[0]["num_emb"])

First row keys in the updated dataset:
dict_keys(['scholar_id', 'cat_ids', 'cat_emb', 'num_ids', 'num_emb'])
num_ids (scaled inputs): tensor([-0.8663, -1.2662,  0.4375])
num_emb (embedding): tensor([ 0.0185,  0.1123,  0.1711, -0.0622,  0.0701,  0.0703, -0.2171,  0.1416,
         0.3679,  0.1457, -0.3624,  0.1867,  0.0149,  0.1227, -0.0679,  0.0362,
        -0.2328, -0.1812,  0.0609, -0.0444,  0.0026, -0.1331, -0.1369, -0.2902,
        -0.2388,  0.2628,  0.0640, -0.3037,  0.1057, -0.2122, -0.0199,  0.2011])

In [21]:
PHD_prefinal_dataset[0]

{'scholar_id': 150,
 'cat_ids': tensor([117,   8,   7,   1,   4]),
 'cat_emb': tensor([-0.0536, -0.1200, -0.0054,  0.0758, -0.0147,  0.0565, -0.0610, -0.0036,
         -0.0930,  0.0555, -0.0396,  0.0412, -0.0317, -0.0834,  0.0974, -0.1482,
         -0.0185,  0.0415, -0.1815, -0.1261,  0.0252, -0.0825, -0.0374,  0.0390,
          0.0032, -0.0658,  0.0674,  0.0053, -0.0444,  0.0385, -0.0905, -0.0797,
          0.0449,  0.1074,  0.0917, -0.0215,  0.0486,  0.0277,  0.0064,  0.0375,
         -0.0416,  0.0087, -0.0865,  0.0190, -0.1329, -0.0959,  0.0765,  0.0646,
          0.0882,  0.0114,  0.1502, -0.0247, -0.0753, -0.0546, -0.0567, -0.0513,
          0.0158, -0.0493,  0.1088, -0.0347,  0.0529,  0.0226,  0.0123,  0.0998,
          0.1051,  0.1086,  0.0592,  0.0393, -0.0944,  0.0304, -0.0555,  0.1885,
         -0.0316,  0.0072,  0.0061, -0.0697,  0.0126, -0.0754, -0.0975,  0.0199,
         -0.0057, -0.0091, -0.0711, -0.0760, -0.0594, -0.0393,  0.1275, -0.0041,
          0.0191, -0.0218,  0.0371, -0.1475, -0.0278, -0.0055, -0.0208, -0.0383,
          0.1104, -0.0897, -0.0134,  0.0986, -0.0167, -0.1240, -0.0402,  0.0817,
          0.0786,  0.0206, -0.0644,  0.0908, -0.0307,  0.0619, -0.0023, -0.1582,
          0.1232, -0.0190,  0.0354,  0.1289,  0.0103, -0.0127,  0.0616,  0.0534,
         -0.2264, -0.0565,  0.0650,  0.0426,  0.0432,  0.1340,  0.0062,  0.0010,
          0.0799,  0.0255, -0.0961, -0.0693, -0.0630, -0.0672, -0.0335, -0.0940,
          0.0190, -0.0975, -0.0441,  0.0439, -0.0459,  0.0576,  0.0728, -0.0134,
          0.0217,  0.0523,  0.0700,  0.1442,  0.0844, -0.0224, -0.0177, -0.0837,
         -0.0817,  0.1942, -0.2464,  0.0871, -0.0607,  0.0609, -0.1500, -0.2187]),
 'num_ids': tensor([-0.8663, -1.2662,  0.4375]),
 'num_emb': tensor([ 0.0185,  0.1123,  0.1711, -0.0622,  0.0701,  0.0703, -0.2171,  0.1416,
          0.3679,  0.1457, -0.3624,  0.1867,  0.0149,  0.1227, -0.0679,  0.0362,
         -0.2328, -0.1812,  0.0609, -0.0444,  0.0026, -0.1331, -0.1369, -0.2902,
         -0.2388,  0.2628,  0.0640, -0.3037,  0.1057, -0.2122, -0.0199,  0.2011])}

In [ ]:
import json
import torch


def convert_tensors_to_lists(obj):
    """Recursively converts PyTorch tensors in a dictionary/list to standard

    Python lists so they can be serialized to JSON.
    """
    if isinstance(obj, dict):
        return {k: convert_tensors_to_lists(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [convert_tensors_to_lists(item) for item in obj]
    elif isinstance(obj, torch.Tensor):
        # Move tensor to CPU, detach from graph, and convert to list
        return obj.detach().cpu().tolist()
    else:
        return obj


# 1. Ensure the directory exists
os.makedirs(
    r"C:\Users\ps302\OneDrive\Desktop\Recommend\src\data\processed\prefinal_dataset",
    exist_ok=True,
)

# 2. Convert all tensors in the dataset to standard lists
serializable_dataset = convert_tensors_to_lists(PHD_prefinal_dataset)

# 3. Save the JSON file in text write mode ("w") instead of binary write mode ("wb")
file_path = r"C:\Users\ps302\OneDrive\Desktop\Recommend\src\data\processed\prefinal_dataset\PHD_prefinal_dataset.json"
with open(file_path, "w") as file:
    json.dump(serializable_dataset, file, indent=4)

print(f"Saved successfully to: {file_path}")

Saved successfully to: C:\Users\ps302\OneDrive\Desktop\Recommend\src\data\processed\prefinal_dataset\PHD_prefinal_dataset.json

In [27]:
import pandas as pd
import torch


def convert_tensors_to_lists(obj):
    """Recursively converts PyTorch tensors to standard Python lists."""
    if isinstance(obj, dict):
        return {k: convert_tensors_to_lists(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [convert_tensors_to_lists(item) for item in obj]
    elif isinstance(obj, torch.Tensor):
        return obj.detach().cpu().tolist()
    else:
        return obj


# 1. Convert any PyTorch tensors in the dataset to standard lists
clean_dataset = convert_tensors_to_lists(PHD_prefinal_dataset)

# 2. Create a pandas DataFrame
df_csv = pd.DataFrame(clean_dataset)

# 3. Save to CSV
csv_path = r"C:\Users\ps302\OneDrive\Desktop\Recommend\src\data\processed\prefinal_dataset\PHD_prefinal_dataset.csv"
df_csv.to_csv(csv_path, index=False)

print(f"Saved dataset as CSV successfully at:\n{csv_path}")

Saved dataset as CSV successfully at:
C:\Users\ps302\OneDrive\Desktop\Recommend\src\data\processed\prefinal_dataset\PHD_prefinal_dataset.csv

In [ ]:
text_col = ["research_interests", "publications", "full_sop_markdown", "expertise"]

In [22]:
text_df = df[["research_interests", "publications", "full_sop_markdown", "expertise"]]
text_df.head()

,research_interests,publications,full_sop_markdown,expertise
0,"[Autonomous navigation for aerial robotics, Mu...",[Learning Safe Maneuvers for Quadrotor Swarms ...,From watching a flock of drones weave through ...,"[Python, C++, Robot Operating System (ROS), Te..."
1,[Satellite remote sensing for climate change m...,[Deep Learning‑Based Atmospheric Correction fo...,When I first examined a series of Sentinel‑2 i...,"[Python, R, MATLAB, Google Earth Engine, ENVI,..."
2,"[Autonomous navigation for aerial robotics, Mu...",[Learning Safe Maneuvers for Quadrotor Swarms ...,From the moment I programmed my first line‑of‑...,"[Python, C++, Robot Operating System (ROS), Te..."
3,[Satellite remote sensing for environmental mo...,[Integrating SAR and Optical Data for Flood Ma...,"Growing up along the Pacific coast of Chile, I...","[Python (NumPy, Pandas, Scikit‑learn), R (sp, ..."
4,[Robust perception for autonomous aerial vehic...,[Safe Multi‑Agent Reinforcement Learning for U...,From the moment I piloted a quadcopter through...,"[Python, C++, ROS2, TensorFlow, PyTorch, JAX, ..."

In [28]:
import pandas as pd


def generate_combined_texts(df, text_cols):
    """Combines specified text columns for each row into a single string.

    Automatically handles lists by joining them with commas and prefixes each
    field with its formatted column name.
    """
    combined_texts = []

    for _, row in df.iterrows():
        row_pieces = []
        for col in text_cols:
            val = row[col]

            # Skip null values
            if pd.isna(val) if not isinstance(val, list) else False:
                continue

            # If the value is a list, join elements with commas
            if isinstance(val, list):
                val_str = ", ".join(
                    [str(item).strip() for item in val if pd.notna(item)]
                )
            else:
                val_str = str(val).strip()

            # Format as "Column name: text value"
            if val_str:
                col_prefix = col.replace("_", " ").capitalize()
                row_pieces.append(f"{col_prefix}: {val_str}")

        # Combine all parts with a period and space
        row_text = ". ".join(row_pieces)
        if row_text:
            row_text += "."

        combined_texts.append(row_text)

    return combined_texts

In [29]:
# 1. Define the text columns you want to merge
text_col = ["research_interests", "publications", "full_sop_markdown"]

# 2. Initialize your target DataFrame if you haven't already
text_df = pd.DataFrame()

# 3. Generate the single combined string for each row and save to text_df["texts"]
text_df["texts"] = generate_combined_texts(df, text_col)

# 4. View a sample of the generated texts
print(text_df["texts"].iloc[0][:500])  # Prints first 500 characters of row 0

Research interests: Autonomous navigation for aerial robotics, Multi‑agent reinforcement learning, Safety‑critical AI for UAV swarms, Sensor fusion and visual‑inertial odometry, Edge AI and low‑power inference, Explainable decision‑making in autonomous systems, Human‑robot interaction in mixed‑initiative missions. Publications: Learning Safe Maneuvers for Quadrotor Swarms via Constrained Reinforcement Learning, Edge‑Optimized Visual‑Inertial Odometry for Low‑Power UAVs. Full sop markdown: From w

In [31]:
text_df.at[0,"texts"]

'Research interests: Autonomous navigation for aerial robotics, Multi‑agent reinforcement learning, Safety‑critical AI for UAV swarms, Sensor fusion and visual‑inertial odometry, Edge AI and low‑power inference, Explainable decision‑making in autonomous systems, Human‑robot interaction in mixed‑initiative missions. Publications: Learning Safe Maneuvers for Quadrotor Swarms via Constrained Reinforcement Learning, Edge‑Optimized Visual‑Inertial Odometry for Low‑Power UAVs. Full sop markdown: From watching a flock of drones weave through a canyon during a summer research retreat, I realized that autonomous systems must reconcile agility with provable safety. This observation sparked my fascination with the paradox of learning‑based autonomy: how to endow machines with the flexibility of deep reinforcement learning while guaranteeing that their actions never compromise mission‑critical constraints.\n\nMy central research question is: How can safety‑critical guarantees be integrated into learning‑based control policies for multi‑agent aerial platforms? I envision this inquiry unfolding across two pillars. The first pillar focuses on constrained reinforcement learning frameworks that embed formal verification into policy optimization. The second pillar addresses edge‑AI architectures that enable real‑time inference on the limited compute budgets of small UAVs, thereby bridging the gap between cloud‑trained models and on‑board execution.\n\nStanford’s Robotics Laboratory, led by Prof. Sergey Levine, offers an unparalleled ecosystem for advancing constrained learning, especially through the lab’s recent work on model‑based RL for manipulation. Simultaneously, Prof. James Kuffner’s expertise in autonomous aerial systems and the Stanford AI Lab’s resources for edge‑computing provide the perfect interdisciplinary environment to explore my dual pillars. The convergence of these faculty interests, coupled with access to the Autonomous Systems Testbed, makes Stanford the ideal place to transform my research vision into tangible breakthroughs.\n\nDuring my master’s program at the University of Michigan, I designed a constrained policy gradient algorithm that reduced collision rates by 42\u202f% in simulated quadrotor swarms (see Publication\u202f[1]). I also built an edge‑optimized visual‑inertial odometry pipeline that runs at 60\u202ffps on a Snapdragon 845 processor while maintaining sub‑centimeter accuracy (see Publication\u202f[2]). These projects required rigorous system integration, from ROS‑based simulation in AirSim to CUDA‑accelerated inference, and yielded two peer‑reviewed papers with a combined citation count of 34. The experience honed my ability to translate theoretical guarantees into deployable software stacks, a skill set I intend to expand under Stanford’s mentorship.\n\nMy long‑term goal is to lead a research group that pioneers safe, scalable autonomy for aerial logistics and disaster response, ultimately translating academic insights into open‑source toolkits for the broader robotics community. I am eager to mentor graduate students, especially those from underrepresented backgrounds, and to collaborate with industry partners such as NASA and Skydio to validate our algorithms in real‑world missions.\n\nReferences\n[1] M. L. Patel, A. Gupta, and S. Levine, “Learning Safe Maneuvers for Quadrotor Swarms via Constrained Reinforcement Learning,” Proceedings of the IEEE International Conference on Robotics and Automation, 2023.\n[2] M. L. Patel and J. Kuffner, “Edge‑Optimized Visual‑Inertial Odometry for Low‑Power UAVs,” IEEE Transactions on Robotics, vol. 39, no. 4, pp. 1021‑1035, 2024..'

In [34]:
text_df.sample(2)

                                                 texts
761  Research interests: Protein structure predicti...
736  Research interests: Remote sensing for nitroge...

In [36]:
import torch


def append_text_embeddings_raw(
    prefinal_dataset, texts, sentence_transformer, device=None
):
    """Encodes a list of text descriptions using a raw SentenceTransformer

    model, and appends each resulting embedding as 'text_emb' to the
    corresponding row in prefinal_dataset.
    """
    if len(prefinal_dataset) == 0:
        return prefinal_dataset

    if device is None:
        # Get the device from the sentence transformer parameters
        device = next(sentence_transformer.parameters()).device

    # Ensure texts is a Python list of strings
    if hasattr(texts, "tolist"):
        text_list = texts.tolist()
    else:
        text_list = list(texts)

    # Generate embeddings using the raw SentenceTransformer model
    with torch.no_grad():
        all_embeddings = sentence_transformer.encode(
            text_list,
            convert_to_tensor=True,  # Return PyTorch tensors directly
            normalize_embeddings=True,  # L2-normalize the output embeddings
            show_progress_bar=True,
            device=device,
        )

    # Append 'text_emb' to each row in the dataset
    for idx, item in enumerate(prefinal_dataset):
        # Shape will be (384,) for all-MiniLM-L6-v2
        item["text_emb"] = all_embeddings[idx]

    return prefinal_dataset

In [37]:
from sentence_transformers import SentenceTransformer

# 1. Initialize raw SentenceTransformer and move to device
text_encoder = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
text_encoder.to(device)

# 2. Append embeddings directly using the raw model
PHD_prefinal_dataset = append_text_embeddings_raw(
    prefinal_dataset=PHD_prefinal_dataset,
    texts=text_df["texts"],
    sentence_transformer=text_encoder,
    device=device
)

# 3. Verify the result
print("First row keys in the updated dataset:")
print(PHD_prefinal_dataset[0].keys())
print("text_emb shape (MiniLM output dimension):", PHD_prefinal_dataset[0]["text_emb"].shape)

c:\Users\ps302\anaconda3\envs\genai\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3249.66it/s]
Batches: 100%|██████████| 27/27 [00:26<00:00,  1.01it/s]

First row keys in the updated dataset:
dict_keys(['scholar_id', 'cat_ids', 'cat_emb', 'num_ids', 'num_emb', 'text_emb'])
text_emb shape (MiniLM output dimension): torch.Size([384])

In [38]:
PHD_prefinal_dataset[0]

{'scholar_id': 150,
 'cat_ids': tensor([117,   8,   7,   1,   4]),
 'cat_emb': tensor([-0.0536, -0.1200, -0.0054,  0.0758, -0.0147,  0.0565, -0.0610, -0.0036,
         -0.0930,  0.0555, -0.0396,  0.0412, -0.0317, -0.0834,  0.0974, -0.1482,
         -0.0185,  0.0415, -0.1815, -0.1261,  0.0252, -0.0825, -0.0374,  0.0390,
          0.0032, -0.0658,  0.0674,  0.0053, -0.0444,  0.0385, -0.0905, -0.0797,
          0.0449,  0.1074,  0.0917, -0.0215,  0.0486,  0.0277,  0.0064,  0.0375,
         -0.0416,  0.0087, -0.0865,  0.0190, -0.1329, -0.0959,  0.0765,  0.0646,
          0.0882,  0.0114,  0.1502, -0.0247, -0.0753, -0.0546, -0.0567, -0.0513,
          0.0158, -0.0493,  0.1088, -0.0347,  0.0529,  0.0226,  0.0123,  0.0998,
          0.1051,  0.1086,  0.0592,  0.0393, -0.0944,  0.0304, -0.0555,  0.1885,
         -0.0316,  0.0072,  0.0061, -0.0697,  0.0126, -0.0754, -0.0975,  0.0199,
         -0.0057, -0.0091, -0.0711, -0.0760, -0.0594, -0.0393,  0.1275, -0.0041,
          0.0191, -0.0218,  0.0371, -0.1475, -0.0278, -0.0055, -0.0208, -0.0383,
          0.1104, -0.0897, -0.0134,  0.0986, -0.0167, -0.1240, -0.0402,  0.0817,
          0.0786,  0.0206, -0.0644,  0.0908, -0.0307,  0.0619, -0.0023, -0.1582,
          0.1232, -0.0190,  0.0354,  0.1289,  0.0103, -0.0127,  0.0616,  0.0534,
         -0.2264, -0.0565,  0.0650,  0.0426,  0.0432,  0.1340,  0.0062,  0.0010,
          0.0799,  0.0255, -0.0961, -0.0693, -0.0630, -0.0672, -0.0335, -0.0940,
          0.0190, -0.0975, -0.0441,  0.0439, -0.0459,  0.0576,  0.0728, -0.0134,
          0.0217,  0.0523,  0.0700,  0.1442,  0.0844, -0.0224, -0.0177, -0.0837,
         -0.0817,  0.1942, -0.2464,  0.0871, -0.0607,  0.0609, -0.1500, -0.2187]),
 'num_ids': tensor([-0.8663, -1.2662,  0.4375]),
 'num_emb': tensor([ 0.0185,  0.1123,  0.1711, -0.0622,  0.0701,  0.0703, -0.2171,  0.1416,
          0.3679,  0.1457, -0.3624,  0.1867,  0.0149,  0.1227, -0.0679,  0.0362,
         -0.2328, -0.1812,  0.0609, -0.0444,  0.0026, -0.1331, -0.1369, -0.2902,
         -0.2388,  0.2628,  0.0640, -0.3037,  0.1057, -0.2122, -0.0199,  0.2011]),
 'text_emb': tensor([-2.0814e-02, -2.8955e-03, -5.2193e-02,  1.0475e-02,  9.2508e-02,
          2.8033e-02, -7.1527e-03, -8.7765e-03, -2.7023e-02,  1.4013e-01,
          3.0943e-02, -6.5161e-02,  3.4189e-02, -1.6494e-02, -1.6024e-02,
          8.3559e-02,  8.1808e-02,  6.0836e-02, -1.1568e-01, -7.7540e-03,
          1.3689e-02,  4.9252e-02,  6.6796e-02,  7.1313e-02, -6.3101e-02,
          1.6721e-02, -2.0447e-02,  1.1077e-02, -5.3822e-02, -2.7370e-02,
          5.1541e-02, -5.6101e-02, -3.0267e-03, -3.2941e-02, -1.1451e-02,
          1.2317e-01, -1.2112e-02, -5.7658e-02, -4.9936e-02,  5.5075e-03,
         -4.1744e-02,  1.1127e-02,  2.7825e-02, -4.2748e-02,  3.5304e-02,
          8.0554e-02,  2.6165e-02, -8.3427e-03,  3.3370e-02, -1.8105e-02,
         -4.4400e-02, -5.1592e-02,  2.6120e-02, -7.2970e-02,  1.1163e-02,
          1.2095e-02,  1.4804e-02,  3.0054e-03,  1.3614e-03, -1.2863e-02,
          1.2362e-02, -9.2981e-02, -1.4577e-02, -1.4901e-02, -6.6872e-02,
          4.4185e-02, -5.1302e-02,  7.0821e-03, -5.0940e-03,  5.2683e-02,
         -9.7579e-03,  6.4050e-03,  2.7558e-02, -3.0758e-02,  2.4710e-03,
          2.3096e-02,  3.5780e-02, -1.0806e-02,  1.8402e-02, -3.5791e-02,
          4.0734e-02, -2.9462e-02, -7.1389e-02,  8.6737e-02,  5.4163e-02,
         -2.1287e-02, -4.9431e-02,  9.1261e-02,  8.5207e-02, -1.4349e-02,
          1.0624e-02, -2.3621e-02, -1.3516e-02, -2.6830e-02,  9.7977e-02,
         -2.6255e-02, -4.6472e-02, -1.6184e-01, -7.8984e-02, -4.9896e-03,
          4.3409e-04, -7.3538e-02,  7.3348e-03,  2.7598e-02,  2.4615e-02,
         -1.0363e-02,  2.7848e-02,  4.2220e-02,  5.3591e-02, -6.2747e-03,
          5.7711e-02, -4.0350e-03,  9.4278e-02,  1.9083e-02, -7.2686e-02,
          3.0617e-02, -6.9036e-02, -1.7817e-02,  2.5608e-02,  8.3804e-02,
         -3.8053e-02, -8.9216e-02,  1.2904e-01,  3.6555e-02,  9.0889e-02,
         -4.6169e-02,  5.5069e-03,  9.3262e-34,  1.5701e-03,  5.0041e-02,
          2.8869e-02,  5.6184e-03,  2.1059e-02, -2.3823e-02,  1.7172e-02,
         -3.5933e-02, -2.0743e-03,  1.4958e-02,  3.1090e-03,  1.3394e-02,
         -2.6074e-02,  6.7572e-02,  8.3027e-02, -4.1048e-02, -2.9627e-02,
         -4.8538e-02, -4.5473e-02, -3.8574e-02,  6.0517e-02, -1.0278e-01,
         -5.4915e-02, -4.4261e-02,  5.3144e-02,  5.1857e-02,  1.5018e-02,
          3.8100e-03,  6.6080e-03,  2.7849e-02, -6.6212e-02,  6.4856e-02,
         -7.8353e-02,  8.1778e-02, -1.3047e-02,  4.5626e-02, -1.0363e-01,
         -5.3767e-02, -8.1513e-02,  5.0496e-02,  2.9188e-02, -1.0768e-02,
          7.2418e-02,  1.3405e-02,  9.8571e-03, -6.6424e-02,  5.2008e-02,
          4.9280e-03, -7.3128e-02, -7.2129e-02, -7.8147e-03,  3.6926e-02,
         -5.2697e-02, -1.3191e-01, -5.7023e-03,  4.4678e-03, -5.6398e-03,
          6.8659e-02, -3.0128e-02,  1.3629e-02,  4.4993e-04, -5.5099e-02,
         -2.8811e-02,  2.8281e-02, -3.0860e-02,  6.0844e-02, -1.1818e-02,
          8.3762e-02,  8.5190e-02, -5.2758e-02, -2.6476e-02,  2.5319e-02,
          2.5221e-02, -7.1271e-02,  2.7206e-02,  3.7304e-02,  2.5126e-02,
         -9.2999e-03,  1.3930e-02,  4.8664e-02,  2.3088e-03,  4.2155e-02,
         -2.8380e-02,  3.2756e-02,  3.4605e-02, -7.4023e-02, -1.5651e-03,
          6.4493e-02, -5.0583e-02,  5.4048e-03, -5.1251e-02, -5.8784e-02,
         -2.0779e-02,  4.8667e-02, -3.6639e-02, -2.3415e-33, -1.7854e-02,
         -6.0240e-02,  3.0804e-02,  4.5498e-02,  1.0930e-02, -3.4034e-02,
         -4.0330e-02, -5.6081e-02,  8.9344e-03, -6.8154e-02, -1.1630e-01,
          2.3744e-03,  3.0186e-02, -2.2295e-02, -2.9469e-02, -3.6546e-02,
         -6.4721e-02, -1.8287e-02,  6.4257e-02, -1.4739e-02,  6.8236e-02,
         -7.8216e-03,  3.8940e-03,  3.7545e-02,  5.7350e-02,  4.2609e-02,
         -3.0563e-02,  1.6091e-03,  5.1345e-02,  1.1401e-01,  3.1784e-02,
         -7.8704e-02, -4.2551e-02,  2.1377e-02, -2.3058e-02,  7.5155e-02,
          2.8673e-02,  2.6443e-03, -9.1979e-02,  8.8824e-02,  1.9156e-02,
         -3.1788e-02, -4.1262e-02, -3.7351e-02,  2.1705e-02, -2.0809e-03,
          2.3344e-02,  2.4602e-02, -8.1705e-02,  2.1171e-02, -5.8768e-02,
          1.5652e-02, -9.6440e-02, -1.3793e-02, -3.7207e-02, -6.8097e-02,
          4.5696e-02,  5.2270e-02,  9.7264e-02, -3.0867e-02, -4.7777e-02,
         -2.4136e-02, -1.0760e-01,  1.0930e-01, -6.3049e-02,  7.3661e-02,
          1.3115e-02,  1.3027e-02,  3.4059e-02,  7.1698e-02, -8.7332e-03,
         -3.7878e-02,  6.8801e-03, -3.9748e-02,  1.2475e-02,  1.5424e-02,
          1.5007e-03, -7.6636e-03, -5.2286e-03, -5.3094e-02,  2.3209e-02,
         -4.7772e-02,  2.2778e-02,  1.1657e-01,  6.2907e-03,  6.0975e-02,
         -1.4306e-02,  2.2496e-02,  1.5950e-02, -2.3437e-02, -4.5794e-02,
         -4.6484e-02, -1.9236e-02,  7.5279e-03, -9.8200e-02, -4.0074e-08,
         -4.4917e-02,  7.3937e-02,  6.3564e-02, -3.5223e-02,  7.3899e-02,
          3.0684e-02,  2.4137e-03, -4.9085e-02,  9.2713e-03, -8.0859e-03,
          3.4769e-02,  2.1530e-02,  3.9778e-02, -7.8837e-02, -5.7112e-02,
          5.5960e-02,  2.2873e-02, -3.9132e-02,  3.0728e-02,  4.6790e-03,
         -1.1552e-02, -1.4818e-02, -6.0092e-02, -1.7507e-02, -1.7874e-02,
         -8.0909e-03, -6.8653e-02,  7.7807e-03,  5.2968e-02,  1.0534e-01,
         -3.7474e-02, -2.0199e-02,  5.0292e-02,  3.4032e-03, -5.8821e-03,
          4.5828e-02, -4.5754e-03, -4.7464e-02,  4.7763e-02, -4.3253e-02,
          2.4157e-02,  1.3064e-01, -2.6545e-02, -3.8520e-02, -4.8658e-03,
          8.1262e-02, -1.2925e-02, -1.1988e-01, -1.0637e-02, -3.0405e-02,
          5.2761e-02, -1.3053e-02,  7.4832e-03,  1.6674e-01,  4.6806e-02,
          2.2492e-02,  7.3975e-02, -1.7783e-01,  6.3565e-02,  9.1530e-02,
         -2.9405e-02,  2.1811e-02, -5.7371e-02, -4.2407e-02])}

In [39]:
import pandas as pd
import torch


def convert_tensors_to_lists(obj):
    """Recursively converts PyTorch tensors to standard Python lists."""
    if isinstance(obj, dict):
        return {k: convert_tensors_to_lists(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [convert_tensors_to_lists(item) for item in obj]
    elif isinstance(obj, torch.Tensor):
        return obj.detach().cpu().tolist()
    else:
        return obj


# 1. Convert any PyTorch tensors in the dataset to standard lists
clean_dataset = convert_tensors_to_lists(PHD_prefinal_dataset)

# 2. Create a pandas DataFrame
df_csv = pd.DataFrame(clean_dataset)

# 3. Save to CSV
csv_path = r"C:\Users\ps302\OneDrive\Desktop\Recommend\src\data\processed\prefinal_dataset\PHD_prefinal_dataset.csv"
df_csv.to_csv(csv_path, index=False)

print(f"Saved dataset as CSV successfully at:\n{csv_path}")

Saved dataset as CSV successfully at:
C:\Users\ps302\OneDrive\Desktop\Recommend\src\data\processed\prefinal_dataset\PHD_prefinal_dataset.csv

In [40]:
import json
import torch


def convert_tensors_to_lists(obj):
    """Recursively converts PyTorch tensors in a dictionary/list to standard

    Python lists so they can be serialized to JSON.
    """
    if isinstance(obj, dict):
        return {k: convert_tensors_to_lists(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [convert_tensors_to_lists(item) for item in obj]
    elif isinstance(obj, torch.Tensor):
        # Move tensor to CPU, detach from graph, and convert to list
        return obj.detach().cpu().tolist()
    else:
        return obj


# 1. Ensure the directory exists
os.makedirs(
    r"C:\Users\ps302\OneDrive\Desktop\Recommend\src\data\processed\prefinal_dataset",
    exist_ok=True,
)

# 2. Convert all tensors in the dataset to standard lists
serializable_dataset = convert_tensors_to_lists(PHD_prefinal_dataset)

# 3. Save the JSON file in text write mode ("w") instead of binary write mode ("wb")
file_path = r"C:\Users\ps302\OneDrive\Desktop\Recommend\src\data\processed\prefinal_dataset\PHD_prefinal_dataset.json"
with open(file_path, "w") as file:
    json.dump(serializable_dataset, file, indent=4)

print(f"Saved successfully to: {file_path}")

Saved successfully to: C:\Users\ps302\OneDrive\Desktop\Recommend\src\data\processed\prefinal_dataset\PHD_prefinal_dataset.json

In [41]:
# Save the dataset directly (keeps tensors, devices, and data types intact)
torch.save(
    PHD_prefinal_dataset,
    r"C:\Users\ps302\OneDrive\Desktop\Recommend\src\data\processed\prefinal_dataset\PHD_prefinal_dataset.pt"
)

In [ ]:
# # Load the dataset back with tensors intact
# PHD_prefinal_dataset = torch.load(
#     r"C:\Users\ps302\OneDrive\Desktop\Recommend\src\data\processed\prefinal_dataset\PHD_prefinal_dataset.pt"
# )